### ISSUE TITLE
Background syncing?

### ISSUE THREAD

**Issue by bleutzinn** [trilbymedia/grav-plugin-git-sync#10]
While working on my Editable plugin to push changes using the Git Sync plugin event `gitsync`, there is a significant delay in the save action from a front-end user perspective. This is because the sync takes about life seconds to complete.

I was thinking about simple having the OS commands execute in the background so I appended a " &" to the $command variable value in 'classes/GitSync.php'. That, unfortunately, doesn't work.

It would be nice to be able to sync in the background.

**Comment by w00fz** [comment]
GitSync comes with a CLI command that you can use to automate and run synchronization in background.
Just a matter of running `bin/plugin git-sync sync` and you should be good.

**Comment by w00fz** [comment]
Also https://github.com/trilbymedia/grav-plugin-git-sync#command-line-interface

**Comment by bleutzinn** [comment]
I've tried to change GitSync to sync in the background but I couldn't make it work.
For my purpose I used `bin/plugin git-sync sync` as you suggested and call it in the background.

Isn't a manual sync already possible by using the 'Synchronise' button in the blueprint settings page? May I suggest to move these Action buttons from the plugin blueprint settings page to the Dashboard? Perhaps as another dropdown button 'GitSync' next to the 'Clear cache' button? Except the 'Wizard' button, I think, as it 'belongs' to the settings page.

Thanks.

**Comment by w00fz** [comment]
This is a good suggestion and something we thought about also, unfortunately it is not yet possible due to a limitation i the admin plugin. 
We plan on expanding the capabilities for 3rd party plugins so that they can add action buttons in dashboard and sidebar but until then I can't add this for gitsync.
And yes, the synchronize and cli command do the same thing.

// Djamil Legato // From iPhone //

**Comment by w00fz** [comment]
I know we have these under our Admin todo list of things to do so for now im going to close this issue until we can re-address it.

Thanks!

**Comment by bleutzinn** [comment]
I agree. If it's helpful when I 'think along' drop me a line!
