### ISSUE TITLE
Wizard Not Working

### ISSUE THREAD

**Issue by sigillumrasa** [trilbymedia/grav-plugin-git-sync#100]
I have installed the latest version of GRAV and your plugin, but the Wizard does not work.

Suggestions?

**Comment by w00fz** [comment]
Are you getting any JS error in the inspector?

**Comment by sigillumrasa** [comment]
sorry, I've been traveling. No, I'm not receiving any errors.

**Comment by okotecki** [comment]
Actually :)

![image](https://user-images.githubusercontent.com/32366290/44204691-fd5eb500-a153-11e8-8887-147b09dd1dc2.png)

**Comment by w00fz** [comment]
Feel free to reopen if this is still an issue.
