### ISSUE TITLE
[Feature Request] support for ssh links

### ISSUE THREAD

**Issue by Moonlight63** [trilbymedia/grav-plugin-git-sync#104]
Currently working on changing the implementation slightly because ssh links like:

`ssh://git@bitbucket.org:22/{user}/{repo}.git`

Don't work because it gets rewritten to something like: 

`ssh://{user}:{password}@git@bitbucket.org:22/CascadeAP/cascadeusersync.git`

**Comment by w00fz** [comment]
What happens if you use `ssh://bitbucket.org:22/{user}/{repo}.git` instead? (note i removed git@)

**Comment by w00fz** [comment]
You can now use `ssh://git@bitbucket.org:22/{user}/{repo}.git` URLs @Moonlight63 , I also added support for SSH Keys. This is available in v2.3.0
