### ISSUE TITLE
[Documentation] Git Sync - Wizard for Gitlab

### ISSUE THREAD

**Issue by coevolving** [trilbymedia/grav-plugin-git-sync#106]
Reading: Step 3 - Setting up the Webhook ...

```
GitLab
1.  Head to the repository on GitLab and click on  dropdown-button at the top right of the page 
```
... the location (of Settings ... Integrations ...) is actually in the left sidebar.

![20180825_gitlab](https://user-images.githubusercontent.com/3098911/44622050-11569500-a87f-11e8-9dc2-5c374e6f56f7.png)

**Comment by w00fz** [comment]
I actually already updated this and will to live with the next release.

Thanks!

**Comment by w00fz** [comment]
https://github.com/trilbymedia/grav-plugin-git-sync/blob/develop/templates/partials/modal-wizard.html.twig#L250
