### ISSUE TITLE
No description of how to manually configure

### ISSUE THREAD

**Issue by Perlkonig** [trilbymedia/grav-plugin-git-sync#109]
I don't use the Admin plugin. I would love to use this plugin, but there is no information whatsoever on how to manually configure it. The default YAML file gives no guidance whatsoever. Assuming there's no way to trigger the wizard outside the Admin plugin, I need *some* information on what the possible config variables are and their allowable ranges. For now I'll have to piece it together from parsing the `blueprints.yaml` file. I'll let you know how it goes. A little more information in the README would sure be nice.

**Comment by w00fz** [comment]
This is something that was proposed already in https://github.com/trilbymedia/grav-plugin-git-sync/issues/13 and that I intend to implement.

Not there yet though.

**Comment by Perlkonig** [comment]
Nah. I just do it manually. I'm already at the command line when I create the content, so it's just a few extra keystrokes to do a push and pull.
