### ISSUE TITLE
Git-Sync Issues regarding hosting on Azure Websites PHP

### ISSUE THREAD

**Issue by jebkor** [trilbymedia/grav-plugin-git-sync#112]
First of, sorry if this is not the correct way to add issues/questions but here goes.

I am trying to setup Grav on a website hosted with Azure, and I am unable to install and use the git-sync plugin. The only lead I have is: 
"The GitSync plugin requires the git binary to be installed and accessible in order to work".
Is this something you have experienced before and possibly have a solution?

Hope it's not a dupe.

**Comment by w00fz** [comment]
I’m not familiar with Azure, meaning I know it but never played with it.

The error means the default location for git on your web server is not found. If you know the location you can set it in the advanced settings of the GitSync plugin. By default it just tries to use `git`, but could be anything. I.e., `/usr/bin/git` or `D:/Git/git.exe`

I haven’t found any documentation abou where the git location would be on azure.

Hope this helps

**Comment by jebkor** [comment]
Thanks for the quick help. Unfortunately, it seems to be the location of git on Azure that is the issue. That's a rather annoying inconvenience. 
Anyway, thanks for your time and for a pretty useful plugin

**Comment by goldjg** [comment]
Location on an Azure Web App (a Windows Web App) is `D:\"Program Files"\Git\bin\git.exe` but even setting that in the Git Sync plugin config doesn't seem to help.
