### ISSUE TITLE
2.0.0-rc.3 feedback

### ISSUE THREAD

**Issue by OleVik** [trilbymedia/grav-plugin-git-sync#115]
Just a couple of notes, to go along with #114:

- The sync-button shows up even before config is done, and clicking it says "GitSync has successfully synchronized with the repository." This button should clearly not be present until the plugin has successfully set up.
- Clicking the background closes the wizard... Making me curse loudly, even though settings are unchanged. An explicit close-button would make for a better UX.
- The instructions are, in general, heavy. To lower the barrier to entry it would be advisable to simplify this as much as possible, and rather leave details and hints to tooltips or the like.
  - Let the Wizard be focused on setup, and rather refer to a longer README; it's almost at the level of "too long, didn't read", leading to "didn't work" because users ignore instructions on screen.
- The Git-icon is off-center:

![image](https://user-images.githubusercontent.com/974717/46243921-33d95200-c3d9-11e8-9d82-8799ba4b5602.png)

**Comment by w00fz** [comment]
All done, cheers!

Re the quick tray icon, I decided to keep it always showing but to properly handle the logic of the click. If you never setup GitSync before, clicking the tray icon will now take you straight to wizard, otherwise it will just do a sync like we know it.
