### ISSUE TITLE
2.0.0-rc.3 feedback - no username/password Next button is enabled

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-git-sync#116]
When on Step 1 of the Wizard, the Next button seems to get enabled once a Git service is chosen - should not the username and password field need to be provided as well to continue?

Here is a screenshot:
![2018-09-29_10-39-16](https://user-images.githubusercontent.com/1812771/46248866-400ee080-c3d4-11e8-9a39-fc3f4a7c6169.png)

Proceeding from this point the Git HTTP address can be entered but then an error message is displayed stating the username is required etc.

Thanks very much!
Paul

**Comment by w00fz** [comment]
Apparently there are cases where you can have no credentials. This is also going to be even less relevant when I’ll intefrate the ssh support

**Comment by paulhibbitts** [comment]
Ah, thanks @w00fz I did not know that. I will close this issue.
