### ISSUE TITLE
Default git sync folder

### ISSUE THREAD

**Issue by coolemur** [trilbymedia/grav-plugin-git-sync#118]
After remote website data is changed plugin syncs changes in root git repo folder.

/pages
/plugins
/themes

Is there a way to set custom location for sync data ?

For example:

/custom-folder/pages
/custom-folder/plugins
/custom-folder/themes

**Comment by paulhibbitts** [comment]
Hi @coolemur , you should be able to add any custom folders within the `user` folder.  For example, I've added an `images` folder within my `user` folder to sync all global site images.

**Comment by coolemur** [comment]
@paulhibbitts Hello. That is right. I can add custom folders to user folder. But when they are mapped into git repo, they appear in git root folder (instead I would like to have for example /git/my-custom-folder/themes or /git/my-custom-folder/themes). How can I customise where those folders appear in git if that is possible ?

**Comment by paulhibbitts** [comment]
Hi @coolemur at this time no. There is a request for support of custom paths which might address this in the future.
