### ISSUE TITLE
GitLab can't trigger the hook because it takes longer then 3 seconds to respond

### ISSUE THREAD

**Issue by khartahk** [trilbymedia/grav-plugin-git-sync#119]
I get this error when trying to trigger the hook from GitLab: `Hook execution failed: Net::ReadTimeout`
When I run the same POST call from Postman 

> you can get the call by going to gitlab.com -> Settings -> Intgrations and click on Edit of the created hook then scroll down and click on View Details for the Recent Delivery you wan't to get it

It works properly. How should I speed up my page? It's not that slow to start with but it takes more then 3 seconds to reposnd to this webhook POST call. Another page on the same server works (not always but most of the time - same nginx config)

**Comment by Jan0707** [comment]
Running into the same issue here (also gitlab)

**Comment by w00fz** [comment]
Unfortunately I am not quite sure how this can be resolved by GitSync. It could be that sometimes your sites are slower to respond to GitLab. It also appears to be hardcoded by GitLab the 3 seconds limit. If it was configurable or longer then this might not be a problem at all.

I have not been able to reproduce this on any of my tests. What kind of setups do you guys have for your Grav sites?

What server? What's your response time? Have you tried on different hosting providers?

**Comment by khartahk** [comment]
We've moved away from Grav to a full static site so I can't give any more details about this. 
I think that the issue was with our web server. 
I'm closing the issue.
