### ISSUE TITLE
Error: pack-objects died of signal 9 fatal

### ISSUE THREAD

**Issue by donnay** [trilbymedia/grav-plugin-git-sync#121]
When attempting to Sync for the first time with GitHub I get the following error:

error: pack-objects died of signal 9 fatal: The remote end hung up unexpectedly fatal: The remote end hung up unexpectedly fatal: write error: Bad file descriptor

TroubleShooting:
- I've created a new gitHub Repo
- I've ensure there is enough Disk Space on my 'local' server (Share web host Rochen.com)

Any additional Info?

**Comment by w00fz** [comment]
This error is not GitSync related, it's coming from GitHub. 

That said, GitHub imposes a limit of 100MB maximum file size (at 50MB you will get a warning) and there is a limit of 1GB size for the entirety  of the repository.

If you exceed any of the limits you will get that error. What you would need to do then is to start using Git LFS which GitHub offers as a paid service.

https://help.github.com/articles/working-with-large-files/

Hope this helps!
