### ISSUE TITLE
Azure Git binary path

### ISSUE THREAD

**Issue by MaxDriller** [trilbymedia/grav-plugin-git-sync#122]
Hi,
I'm running grav on azure in a windows based envrionment based on the documentation. 
I've installed the git sync plugin but the wizard is not coming up for me. The path to my git binary is D:\Program Files\Git\bin and it has been entered in the advanced settings; still the wizard refuses to come up and keeps showing me the popup about git needing to be installed. 

The binary itself is called git.exe. I've tried supplying the path with and without the binary name and its extension. I've also tried copying the binary into the plugin folder to no avail. 

Is there something else I can try?

**Comment by goldjg** [comment]
I'm seeing exactly the same behaviour on an Azure Web App (using windows rather than Linux).  Currently working on an Azure WebJob that runs `php bin/grav backup` then runs `D:\"Program Files"\Git\bin\git.exe` to push the backup up to the repo. Got the first bit done, working on the git push just now. Will share my code if successful.

**Comment by goldjg** [comment]
I’ve found that I can run from the Kudu debug console, but still not from the Git Sync plugin.
I also created a php script to run php info when accessed through the site (and this works), but a php script to issue an `echo exec(‘git —version')` works when executed on the console but returns an empty page when run from the browser. 
`exec()` and `escapeshellarg()` aren’t disables but I think some other azure lockdown might be at play here (I’m using a shared Web App, perhaps a dedicated one will have less restrictions).

I did find that as well as `D:\home\site\wwwroot\` there’s also a `D:\home\site\repository\` which contains the code deployed from GitHub, prior to being built by msbuild as part of the deployment (Azure Web Apps can auto-deploy from a git repo using a web hook - I only wanted Git Sync so I could move some files back up to GitHub e.g. Grav backups.)

**Comment by w00fz** [comment]
Guys I just tested this and the issue is you can't escape the binary path like you are doing (quotes on "Program Files", the whole command has to be escaped.

`"D:\Program Files\Git\bin\git.exe"` <- try that and it will work.

I'll make sure to explain this better in the documentation

**Comment by w00fz** [comment]
Something like this, what do you guys think?

<img width="359" alt="azure docs" src="https://user-images.githubusercontent.com/11734/53063447-002ac180-3479-11e9-9104-137f0c980782.png">

**Comment by goldjg** [comment]
Gah! Staring me in the face (and it’s not like I’ve not hit my head off that before in scripting)!

I would maybe tweak the wording as if someone is running a Windows VM on Azure (or indeed on their own computer) they may have a different path to git than on a Azure Web App (Windows). Perhaps just state that the path shown is for a Web App on Windows but the path may vary by installation e.g on a VM or physical computer.
