### ISSUE TITLE
Undefined index 

### ISSUE THREAD

**Issue by alex-mohemian** [trilbymedia/grav-plugin-git-sync#134]
After updating to 2.0.1 which added the customized git commit message, the plugin errors with `Undefined index 'message'`.

The settings need to be saved once for the error message to go away. Maybe a default should be added in case the `message` property does not exist yet.

**Comment by ginkgomzd** [comment]
experienced the same. 
Didn't seem associated with an upgrade.

Work-around (re-save plugin config) did clear the problem.

**Comment by w00fz** [comment]
Do you guys think this could be related to #96 ?

**Comment by ginkgomzd** [comment]
:+1: :1st_place_medal:
