### ISSUE TITLE
GitSync auto-commits to incorrect path

### ISSUE THREAD

**Issue by bewards** [trilbymedia/grav-plugin-git-sync#137]
Being relatively new to Grav I may not fully understand why it's doing this, but when I add a plugin or a blog page via admin panel on my live site, the sync commits blog page files (from the server) under`/pages/01.blog/[blog page]` instead of `/user/pages/01.blog/[blog page]`, as well as `/plugins/` instead of `/user/plugins/`. 

When I pull these changes down locally, none of the pages i've published live or plugins are available and have to be moved in to the user folder. 

Then if I commit and push up some custom css under `user/themes/mytheme/css` or add a partial under `user/themes/mytheme/templates/partials` in order to override some markup from the default theme (that works locally) and hit **Synchronize**, I don't see these files being added to that directory location on the server.

In the public site admin panel I do have the wizard configured for Pages, Themes, and Plugins.

**Comment by nicolay-zlobin** [comment]
The same question.

**Comment by w00fz** [comment]
That doesn't look right indeed. 
Can you guys describe your environment, settings as well as how is your repository structure? Is it just the user folder?

Also you can run `bin/plugin git-sync status` to get some configurations view. Please be careful with what you paste in here as this is publicly viewable.

Another thing you can check is how your sparsecheckout git config look like, from the root of the project run a `cat user/.git/info/sparse-checkout`

**Comment by nicolay-zlobin** [comment]
I don't know whether it's the right method or not but seem I solved it this way: 
1. Install The Grav on the server with the first method of the install guide.
2. Install and set up Git Sync on the server.
3. Install Grav on the local machine.
4. Remove all folders from user folder on the local machine (except accounts)
5. Pull to user folder what Sync committed to git.

The issue was when I tried to set up Sync with existing the whole repository (as we can get with option 3: Install from GitHub from install guide)

**Comment by bewards** [comment]
My Grav site is hosted on Linode Ubuntu 18.04 LTS.

Running `bin/plugin git-sync status` locally gives me the following (user/pass actually came up as null):
![image](https://user-images.githubusercontent.com/3927169/54691769-356b1380-4afa-11e9-8675-ddb17ac6d61b.png)

Running `cat user/.git/info/sparse-checkout` locally returns "No such file or directory" as there is no **.git** directory underneath `/user`.

**Comment by w00fz** [comment]
Looks like your gitsync instance is misconfigured or somewhat broken. You should definitely have a .git folder under user for all the git configurations of your repo and sparse checkout.

Try enabling gitsync logging and try going through the wizard once again. Also try to save the plugin after the wizard is done.

**Comment by bewards** [comment]
Thanks @w00fz - resolved by walking through the wizard again and updating the web hook to ssl and re-saving with the webhook secret. After saving, I now see the `.git` directory under `/user`. 

This can be closed.

**Comment by w00fz** [comment]
Awesome, glad it’s resolved 👍
