### ISSUE TITLE
RPC Failed HTTP Error 404

### ISSUE THREAD

**Issue by k1ngf15h3r** [trilbymedia/grav-plugin-git-sync#138]
Tried to set up git sync with the Learn2 with GitSync Grav Skeleton. Created webhook and tested connection successfully but when trying to syn I get the following error.

error: RPC failed; result=22, HTTP code = 404 fatal: The remote end hung up unexpectedly

I am using a self hosted gitlab. Previous syncs with GitSync run without problems.

**Comment by w00fz** [comment]
This sounds like some connection issue. I know it's obvious but I would try recheck all the settings, username, password, repository.

Test with the wizard also, you can test the connection there which makes things a bit easier.
