### ISSUE TITLE
Ability to use Grav Admin username as "Commiter Name"

### ISSUE THREAD

**Issue by robertbak** [trilbymedia/grav-plugin-git-sync#14]
Useful for keeping track who's making changes on Grav installs with multiple users.

On admin actions like ```onAdminSave``` there's ```$this->grav['session']->user->fullname```

**Comment by paulhibbitts** [comment]
I've also come up with a use case for this one, it would be a very helpful feature.

**Comment by w00fz** [comment]
Good idea!

**Comment by paulhibbitts** [comment]
Thanks for considering that request @w00fz. I can see it also VERY valuable re: Ron's in-line editor plugin passing the current user when calling GitSync👍

**Comment by w00fz** [comment]
I'm thinking this could be an option in the plugin where you can choose to use either the Git Repository user, the current Grav session user or the current Grav session fullname. So that it applies to the plugin globally.

**Comment by paulhibbitts** [comment]
That sounds nice and flexible @w00fz

**Comment by w00fz** [comment]
This is now implemented with 4 options to pick from.

![plugin git sync grav 2017-02-18 16-59-08](https://cloud.githubusercontent.com/assets/11734/23098139/99afc6ca-f5fb-11e6-97be-a8a2dbf27bba.png)

Note that when synchronizing via CLI, the Git User is the only viable option and will override any other setting.
