### ISSUE TITLE
not compatible with grav 1.6.8

### ISSUE THREAD

**Issue by AEnterprise** [trilbymedia/grav-plugin-git-sync#140]
when trying to save a page the git sync plugin errors:

```[2019-04-24 09:47:12] grav.CRITICAL: Call to a member function get() on array - Trace: #0 /storage/web/gearbot/user/plugins/git-sync/classes/GitSync.php(302): Grav\Plugin\GitSync\GitSync->addRemote('origin', 'https://github....', true) #1 /storage/web/gearbot/user/plugins/git-sync/git-sync.php(210): Grav\Plugin\GitSync\GitSync->sync() #2 /storage/web/gearbot/user/plugins/git-sync/git-sync.php(365): Grav\Plugin\GitSyncPlugin->synchronize() #3 /storage/web/gearbot/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\GitSyncPlugin->onAdminAfterSave(Object(RocketTheme\Toolbox\Event\Event), 'onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /storage/web/gearbot/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #5 /storage/web/gearbot/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #6 /storage/web/gearbot/system/src/Grav/Common/Grav.php(365): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #7 /storage/web/gearbot/user/plugins/admin/classes/admincontroller.php(657): Grav\Common\Grav->fireEvent('onAdminAfterSav...', Object(RocketTheme\Toolbox\Event\Event)) #8 /storage/web/gearbot/user/plugins/admin/classes/admincontroller.php(563): Grav\Plugin\Admin\AdminController->taskSavePage() #9 /storage/web/gearbot/user/plugins/admin/classes/adminbasecontroller.php(110): Grav\Plugin\Admin\AdminController->taskSave() #10 /storage/web/gearbot/user/plugins/admin/admin.php(809): Grav\Plugin\Admin\AdminBaseController->execute() #11 /storage/web/gearbot/user/plugins/admin/admin.php(434): Grav\Plugin\AdminPlugin->initializeController('save', Array) #12 /storage/web/gearbot/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\AdminPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #13 /storage/web/gearbot/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #14 /storage/web/gearbot/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #15 /storage/web/gearbot/system/src/Grav/Common/Grav.php(365): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #16 /storage/web/gearbot/system/src/Grav/Common/Processors/PagesProcessor.php(31): Grav\Common\Grav->fireEvent('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #17 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #18 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /storage/web/gearbot/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #21 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /storage/web/gearbot/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #24 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /storage/web/gearbot/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #27 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /storage/web/gearbot/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #30 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /storage/web/gearbot/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #33 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /storage/web/gearbot/system/src/Grav/Common/Processors/RequestProcessor.php(49): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #36 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /storage/web/gearbot/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #39 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /storage/web/gearbot/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #42 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /storage/web/gearbot/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #44 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #45 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /storage/web/gearbot/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #47 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #48 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /storage/web/gearbot/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #50 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #51 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #52 /storage/web/gearbot/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #53 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #54 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #55 /storage/web/gearbot/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #56 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #57 /storage/web/gearbot/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #58 /storage/web/gearbot/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #59 /storage/web/gearbot/index.php(53): Grav\Common\Grav->process() #60 {main} [] []```

**Comment by w00fz** [comment]
Did you setup GitSync through the wizard and tried Testing the connection?
Also what PHP version are you using?

**Comment by AEnterprise** [comment]
yes i setup through the interface and it worked fine until i updated to 1.6.8

using php version 7.3

**Comment by w00fz** [comment]
Are you able to try a fresh 1.6.8 setup (for testing) to see if that helps? I cannot reproduce the error you are seeing.

**Comment by Plumf** [comment]
I install new site with Grav 1.6 and i try install git sync plugin's but I've the same error. You need more informations about the installation ?

**Comment by w00fz** [comment]
Yes also can you try going through the wizard and Testing the connection, does that cause any error?

**Comment by Plumf** [comment]
I'm not sur to understand. I tried install plugin with admin's panel and the site show an error's page like this : 
![](https://framapic.org/dgz4cR6i4JFK/IFMyyvaw9965)

**Comment by rhukster** [comment]
The message says that exec has been disabled by your hosting provider. Exec is required to use gitsync. They may be able to enable it for you, but if not you may have to change providers if you want to use gitsync.

**Comment by AEnterprise** [comment]
updating to 1.6.9 fixed the problem for me so looks like the cause was on grav's side somewhere (sorry for the delay RL got in the way)
