### ISSUE TITLE
unable to now add subfolders of 'themes'

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-git-sync#141]
Hi @w00fz ,

I've noticed that somewhere along the way past 2.0 I seem to be unable to add a subfolder for syncing, for example `themes/mytheme`. Here is the error message I see:

![2019-05-01_16-18-24](https://user-images.githubusercontent.com/1812771/57049459-05e91400-6c2d-11e9-8a02-b27f001cab41.png)

If I manually edit the gitsync.yaml file with the subfolder all works as expected.

Please let me know if any more info is helpful etc.

Thanks very much,
Paul

**Comment by w00fz** [comment]
That is odd as nothing has really changed... I will test this out and report back.

**Comment by paulhibbitts** [comment]
Thanks very much @w00fz !

**Comment by w00fz** [comment]
I believe some new grav/form/admin changed the behavior of the select vs selectize field and caused the validation to break.

I have now switched the field over to selectize. This fixed the problem for GitSync and I released 2.0.5.

Cheers.
