### ISSUE TITLE
Grav Container password not persistent

### ISSUE THREAD

**Issue by AntoinePerry** [trilbymedia/grav-plugin-git-sync#146]
Hello,

I have a grav container with git-sync. my problem is that each time the container is restarted, the password is lost and therefore no more synchronisation. Wwhere this password is saved ?
thanks

**Comment by w00fz** [comment]
The password is stored in the `user/config/plugins/git-sync.yaml` ... However, it is encrypted and so it's not that easy for you to generate it manually every time.

One thing I could do is to add to the `bin/plugin git-sync` command a `passwd` (password change) that let's you properly store a new encrypted password in the config. 

In the meantime, for your interest, this is how a password gets generated: https://github.com/trilbymedia/grav-plugin-git-sync/blob/develop/classes/Helper.php#L98-L101

**Comment by w00fz** [comment]
This will now be available as a command line `bin/plugin git-sync passwd -p <your_password>`
