### ISSUE TITLE
user dir as submodule: git-sync/classes/GitSync.php incorrectly assumes .git is a directory

### ISSUE THREAD

**Issue by draeath** [trilbymedia/grav-plugin-git-sync#147]
git-sync v2.0.5 on grav v1.6.9 - have not yet tested newer versions.

When keeping my whole grav instance in git, I must use a submodule for the user directory so that git-sync is able to operate.

However, certain changes in the admin panel (such as configuration of git-sync itself) drives git-sync to try to create or access '/.git/info/sparse-checkout' - see git-sync/classes/GitSync.php line 142:

    $file = File::instance(rtrim($this->repositoryPath, '/') . '/.git/info/sparse-checkout');

This is bad behavior. In the case of git submodules, .git is a file and not a directory. For example, mine contains the text:

    gitdir: ../.git/modules/user

Please consider checking if `.git` is a file, and if it is checking for `gitdir: ` and following that path for this operation, instead.

**Comment by w00fz** [comment]
Yeah... I haven't really tested GitSync with submodules at all, that usually isn't a common setup for the Grav `user`.

If you could help figure out a fix and propose the change that would be helpful
