### ISSUE TITLE
fatal: Out of memory? mmap failed: Cannot allocate memory 

### ISSUE THREAD

**Issue by samuel-fonseca** [trilbymedia/grav-plugin-git-sync#148]
I installed and setup git-sync just fine, but when trying to sync the content via the `webhook` I get this error:

```
fatal: Out of memory? mmap failed: Cannot allocate memory
```

I have git logs enabled, the logs are as follows:

```log
[2019-09-04 15:57:16] grav.NOTICE: gitsync[command]: LC_ALL=C cd /home/public_html/user/ && git status pages 2>&1 [] []
[2019-09-04 15:57:16] grav.NOTICE: gitsync[output]: fatal: Out of memory? mmap failed: Cannot allocate memory [] []
```

Has anyone experienced this issue. I attempted searching but found nothing through the issues page.

**Comment by w00fz** [comment]
Looks like your VPS might not have enough memory, where is the site running on?

**Comment by samuel-fonseca** [comment]
Arvixe business shared server ...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by w00fz** [comment]
What's the specs? Might have to bump the memory.
Some other things i see by googling is that it could be caused by an older version of git.

**Comment by samuel-fonseca** [comment]
They don't give the specifics, but the memory is plenty fast, I used git in the back end for pretty much anything. I'm not sure that they would increase it anyways 😔

I tried googling, but like I said, could not find a relavant solution to this specific issue.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by samuel-fonseca** [comment]
> Some other things i see by googling is that it could be caused by an older version of git.

@w00fz  The current version of git running on the server is 2.17.1

**Comment by w00fz** [comment]
In case this was still not resolved, seems to be related to git on your server: https://stackoverflow.com/a/6812201
