### ISSUE TITLE
git "edit this page" button presents wrong url for gitea

### ISSUE THREAD

**Issue by valahna** [trilbymedia/grav-plugin-git-sync#150]
When using a git server besides github (did not try to compare with gitlab), the auto-generated button link is generating an incorrect url. This is what it generates:

`https://<git_server>/<user>/<reponame>/blob/master/pages/01.basics/chapter.md`

But for gitea (and likely gogs as well, could be wrong) it should be:

`https://<git_server>/<user>/<reponame>/src/branch/master/pages/01.basics/chapter.md`

Is there a setting in a config file somewhere I can change this? I looked in `/user` but was unable to find an appropriate setting.

**Comment by paulhibbitts** [comment]
Hi @valahna , what theme or skeleton are you seeing this in? It is likely an issue of the theme vs. this plugin.

Thanks,
Paul

**Comment by valahna** [comment]
I apologize @paulhibbitts , I found the settings in the theme to update the URL, I must have missed it the first 10 tens I looked -.-; 

It works as expected, this was a pebcak issue :)

**Comment by paulhibbitts** [comment]
🙂That's great to hear you got it going @valahna , hope you find the theme useful!
