### ISSUE TITLE
Last delivery was not possible. Invalid HTTP response:404

### ISSUE THREAD

**Issue by nunocalaim** [trilbymedia/grav-plugin-git-sync#157]
I am trying to set up a clean grav install with git-sync plugin.

I followed the instructions as in [here](https://www.youtube.com/watch?v=avcGP0FAzB8)

When I add a webhook to my github repository, on github I see the following error: Last delivery was not possible. Invalid HTTP response:404

Not surprisingly when I edit a page I get the error: The requested URL returned error: 403 Forbidden while accessing https://nunocalaim:{password}@github.com/nunocalaim/iesintra.org.git/info/refs fatal: HTTP request failed

The only possible difference I am making is that I have all my grav instalation on a subfolder on my server (this folder is called dev for development. as I it is not ready to go public just yet) Would this be a problem?

**Comment by w00fz** [comment]
That should be a problem. What I would do is to try and reach that URL manually via browser.

403 means the authorization failed
404 means the page is not there for GH

If you can manually try to go through those paths, you should be able to figure out what's going on
