### ISSUE TITLE
Multiple security reports 

### ISSUE THREAD

**Issue by RCheesley** [trilbymedia/grav-plugin-git-sync#158]
Hi there,

Dependabot just went a little crazy on my Grav repo, pointing at multiple dependency issues with this plugin. As far as I'm aware, I'm up to date with the latest version of the plugin, so not sure if there are going to be updates in the future to address these?

The main critical alerts seem to be lodash, mixin-deep, js-yaml and eslint-utils.

**Comment by w00fz** [comment]
I fixed them, thanks

**Comment by RCheesley** [comment]
Perfect thank you! Presume that a release will come out in due course? Much appreciated!

**Comment by w00fz** [comment]
Hope this week, there's some other changes in the pipe that will make GitSync depending on minimum Grav 1.6 and I'm trying to make sure there's no bad implications with that.

You could download the zip from develop if you have urgency of using the latest and greatest.

**Comment by RCheesley** [comment]
OK that's perfect, thank you for the info!

**Comment by RCheesley** [comment]
Any ideas when the next release might be coming? Will grab the develop zip if it's not going to be imminent as we're about to launch our platform and would rather do that without known vulnerabilities :)

**Comment by w00fz** [comment]
Sorry I’ve been focused on other projects and I forgot about the release of gitsync.
I’ll try to get it out today.

**Comment by RCheesley** [comment]
Wonderful, thank you very much! :)

**Comment by w00fz** [comment]
Released now! Should be appearing on GPM soon.

Thanks
