### ISSUE TITLE
Grav 1.7RC with Flex Pages and Grav 1.6.21 unable to setup Git Sync

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-git-sync#159]
Hi @w00fz , I've started doing more testing with 1.7 Flex Pages and I think I've come across an issue:

1) Update new Grav install with 1.7RC6
2) Enable Flex pages front-end
3) Run Git Sync Wizzard and complete

The wizard when completed will re-appear, and you will see the following error message:

<img width="1558" alt="2020-02-11_18-07-16" src="https://user-images.githubusercontent.com/1812771/74296993-58964700-4cfa-11ea-90f8-1c80e51c10f1.png">

If I can be of any help re: testing more info etc. please let me know.

BTW, it seems that if you install Git Sync on 1.7RC6, and THEN turn on Flex Pages front-end things work fine (though sometimes there might be up to a minute before change is reflected on site).

Thanks very much,
Paul

**Comment by w00fz** [comment]
Thanks, we'll take a look!

/cc @mahagr

**Comment by mahagr** [comment]
@w00fz This is because of the plugin has strict mode turned on and there was a bug preventing blueprint strict mode from working.

**Comment by mahagr** [comment]
Looks like I cannot change the title, but this would happen also with the old pages. :)

**Comment by paulhibbitts** [comment]
Hi @w00fz , I've just had someone contact me about this error now happening with the latest Stable Grav release, and I can confirm that the error is also happening there now too. 

If I can be of any more help please let me know.

**Comment by mahagr** [comment]
This is the fix from Grav 1.6.20 causing the issue:
https://github.com/getgrav/grav/issues/1273

**Comment by w00fz** [comment]
Can you make gitsync right then 🙂?

**Comment by mahagr** [comment]
For now, I reverted the `validation: strict` fix in Grav 1.6, but it does not fix issues in Grav 1.7.

**Comment by w00fz** [comment]
Thanks @mahagr

**Comment by mahagr** [comment]
I'm going to reopen this as it's not fully solved in Grav 1.7.

In fact, I was not able to reproduce the issue; saving worked just fine for me even with the strict limitations.

I'm not sure why there's `data[test_var]` and where it is coming from. All the variables that shouldn't be saved into configuration should be outside of data anyway, though for me it was like that.

**Comment by w00fz** [comment]
@paulhibbitts do you have that text_var field in the gitsync plugin or saves in the user config somewhere? It is a bit odd it fails on that field.

**Comment by paulhibbitts** [comment]
Hi @w00fz I don't think I  added anything on my end... I will try to setup an online test version going that you can take a look at too.

**Comment by paulhibbitts** [comment]
@w00fz , I've got a test site going online with the issue - will connect on Discord with login info etc.

**Comment by paulhibbitts** [comment]
Thanks to the detective work of @w00fz I tracked down this issue to a deprecated item in the plugin config file - solved by removing this item (which was caught due to the improvements for strict validation).
