### ISSUE TITLE
fatal: unable to access 'https://github.com/JaleshJalesh/testing.git/': The requested URL returned error: 403

### ISSUE THREAD

**Issue by ghost** [trilbymedia/grav-plugin-git-sync#163]
team, please check as to why i am unable to push /pull on github?below is the steps i followed

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ git config --list
pack.packsizelimit=2g
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=E:/Git/mingw32/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
merge.tool=kdiff3
mergetool.kdiff3.path=D:/Program Files/KDiff3/kdiff3.exe
diff.guitool=kdiff3
difftool.kdiff3.path=D:/Program Files/KDiff3/kdiff3.exe
user.email=mail...@gmail.com
user.name=Jalesh
user.username=
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/JaleshJalesh/testing.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ ssh-keygen -t rsa -b 4096 -C "mail...@gmail.com"
Generating public/private rsa key pair.
Enter file in which to save the key (/d/Users/jalesh/.ssh/id_rsa):
Created directory '/d/Users/jalesh/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /d/Users/jalesh/.ssh/id_rsa
Your public key has been saved in /d/Users/jalesh/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:Q3Q0p[snip] mail...@gmail.com
The key's randomart image is:
+---[RSA 4096]----+
|        ..+ .    |
|       . o +   + |
[snip]
|   .oo+..      o |
+----[SHA256]-----+

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ eval $(ssh-agent -s)
Agent pid 1511

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ ssh-add ~/.ssh/id_rsa

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ tail ~/.ssh/id_rsa.pub
ssh-rsa AAAAB3Nza[snip...] mail...@gmail.com

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ git remote add origin https://github.com/borntospark0/latest.git
fatal: remote origin already exists.

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$ git push -u origin master
remote: Permission to JaleshJalesh/testing.git denied to borntospark0.
fatal: unable to access 'https://github.com/JaleshJalesh/testing.git/': The requested URL returned error: 403

Jalesh@jalesh-PC MINGW32 /e/GitTutorialFolder (master)
$

**Comment by w00fz** [comment]
First off, just letting you know I edited your issue and removed some sensible data that you had shared. like your email and the full pub RSA.

Regarding the issue, this is just a Git issue and not really related to GitSync, but, as the last command you perform says:

```
$ git push -u origin master
remote: Permission to JaleshJalesh/testing.git denied to borntospark0.
fatal: unable to access 'https://github.com/JaleshJalesh/testing.git/': The requested URL returned error: 403
```

You are trying to push as the user `borntospark0` which doesn't have permission to do so for the `JaleshJalesh/testing` repository. Moreover, I'm not even sure that user exists [since when you try to reach it on GitHub, returns a 404](https://github.com/borntospark0)
