### ISSUE TITLE
bin/plugin git-sync sync throws Class not found exception

### ISSUE THREAD

**Issue by br0tkasten** [trilbymedia/grav-plugin-git-sync#167]
git-sync version 2.1.0

# php7 -v
`
PHP 7.3.16 (cli) (built: Mar 23 2020 13:33:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.16, Copyright (c) 1999-2018, by Zend Technologies
`
# sudo -u lighttpd bin/plugin git-sync -V
`
Grav Plugins Commands 1.6.23
`
# sudo -u lighttpd bin/plugin git-sync sync
`
PHP Fatal error:  Uncaught Error: Class 'Grav\Plugin\GitSync\GitSync' not found in /var/www/localhost/grav-admin/user/plugins/git-sync/cli/SyncCommand.php:25
Stack trace:
#0 /var/www/localhost/grav-admin/system/src/Grav/Console/ConsoleCommand.php(41): Grav\Plugin\Console\SyncCommand->serve()
#1 /var/www/localhost/grav-admin/vendor/symfony/console/Command/Command.php(255): Grav\Console\ConsoleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/localhost/grav-admin/vendor/symfony/console/Application.php(917): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/localhost/grav-admin/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Grav\Plugin\Console\SyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/l in /var/www/localhost/grav-admin/user/plugins/git-sync/cli/SyncCommand.php on line 25
`
reinstalling git-sync plugin does not fix the issue.
Issue occurred first about 2 weeks ago (grav and plugins are automatically updated once a day).

**Comment by mxiia** [comment]
I have the same issue.

`init` `status` and `sync` all give similar errors. 

Fresh install

**Comment by markus-mohemian** [comment]
Same issue here. Reinstalling the plugin does not fix the issue for me.

**Comment by w00fz** [comment]
Is this limited to `bin/plugin git-sync` or is this happening for every `bin/plugin` command?
For example, does `bin/plugin error log` work for you?

**Comment by w00fz** [comment]
Actually I can replicate the issue. Looks like the class needs to be loaded manually now. Somewhere in the Grav changes, I missed this breaking change.
