### ISSUE TITLE
error 500 to configure webhook on github

### ISSUE THREAD

**Issue by juliemar** [trilbymedia/grav-plugin-git-sync#169]
I'm trying to configure the plugin following the wizard but is not working. 

![image](https://user-images.githubusercontent.com/643779/81968170-6b1e6600-95f2-11ea-8a68-ffc7bdeb3389.png)

**Comment by w00fz** [comment]
Try enabling logging in the advanced section of GitSync. Then you should have more details about what's actually failing in the grav.log
