### ISSUE TITLE
Infinitely entering wizard

### ISSUE THREAD

**Issue by jkransen** [trilbymedia/grav-plugin-git-sync#171]
I run the wizard to add a GitLab repo. All steps through the  wizard are successful, but after saving, it starts the wizard again. I close the wizard, and click "Save" in the top right corner. It starts the wizard again. When trying to leave, it warns for unsaved changes. There is no local .git subdir in my user folder. There was before, but I had to remove it to get rid of the "unrelated histories" error message. I expected it to be re-created, but it isn't.

Git Sync 2.1.0
Remote Git repo: gitlab.com
Grav 1.6.25
Grav Admin 1.9.14

Update: Removed entire Grav project and recreated from scratch. This time connected to GitHub instead of GitLab. Same result. Note that I do get a successful login popup when testing the connection.

Update 2: Another thing where I may deviate is that I am running Nginx instead of Apache. This is the config snippet:
```
    root /var/www/mysite.com;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
      try_files $uri =404;
      fastcgi_pass unix:/run/php/php7.2-fpm.sock;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
    }
```

Update 3: It is a private repo, but I assume that doesn't make a difference, as it can connect with the provided token.

**Comment by w00fz** [comment]
Hey @jkransen , [a new release v2.1.1](https://github.com/trilbymedia/grav-plugin-git-sync/releases/tag/2.1.1) is out and should address a regression introduced that would cause that unrelated histories error you were seeing.

Give it a go!

**Comment by jkransen** [comment]
Thanks for the effort. I did give it a try, and it still re-enters the wizard after successfully testing the connection to Gitlab. Also, even though test succeeded, my contents do not show up in Gitlab.
