### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by panthia** [trilbymedia/grav-plugin-git-sync#174]
Plugin was working fine but I changed my token and now I get error 404 on my Brave browser. Firefox finds the github page without issue. 

I tried clearing the cache of the Brave browser but can't seem to get it to work again. As a test I tried the edit page link on chrome and also got the 404 error. 

Does anyone know what I am missing here?

**Comment by w00fz** [comment]
404 error when doing what? Reaching your site or trying to connect gitsync to the repository? 
Are you saying that Firefox/Chrome works and only Brave doesn't ?
