### ISSUE TITLE
Not syncing themes folder

### ISSUE THREAD

**Issue by millernw** [trilbymedia/grav-plugin-git-sync#178]
First, the clickable check boxes during the setup wizard - the ones that let you choose which folders to replicate to Github - I tried adding "themes" in the wizard and it didn’t take, then I tried re-running the wizard and that didn’t take. Finally I uninstalled the plugin, reinstalled, and tried clicking those options again… didn’t work.
I've also tried adding "themes" to the Basic Settings > folders to sync but I'm still not getting GitSync to push that folder and its contents to Github. Am I doing something wrong, or is this a bug?
I'm using Gitsync v2.1.1

**Comment by DidierLmn** [comment]
I have the same issue. I've tried adding 'plugins', but it doesn't get synced either. Only 'pages' gets synced.

**Comment by MattAppleton** [comment]
We also have the same issue — even though our .gitignore has both !/pages and !/themes... this is occurring with a local install running off MAMP...

**Comment by MattAppleton** [comment]
To clarify — if I add a NEW file, say to templates... that gets synced...

If I amend an existing file, that does NOT get synced...

**Comment by wblondel** [comment]
Same issue as of march 2021

**Comment by w00fz** [comment]
This is now fixed, will be available in the next release that I plan to get out soon
