### ISSUE TITLE
Syncing on page saves even with 'Sync on save' set to off

### ISSUE THREAD

**Issue by davay42** [trilbymedia/grav-plugin-git-sync#179]
I have GitSync syncing changes to the repo on every page save even with the option 'Sync on page save' set to off (actually all of the sync options are off). It makes editing the site much slower and creates unnecessary commits in the repo. Seems like a bug. I'm on recent Grav 1.7.

**Comment by w00fz** [comment]
Maybe this is an issue introduced by Flex Objects? @mahagr any clue what this could be?

**Comment by biozic** [comment]
Same problem here (Grav v1.7.0-rc.15, Git-Sync v2.1.1)

**Comment by w00fz** [comment]
This was resolved with the release of Flex Objects
