### ISSUE TITLE
Please advise how to solve below issue  

### ISSUE THREAD

**Issue by Muh-asif04** [trilbymedia/grav-plugin-git-sync#186]
remote: Permission to Muh-asif04/michaelkors_app.git denied to Babarkhan493.
fatal: unable to access 'https://github.com/Muh-asif04/michaelkors_app.git/': The requested URL returned error: 403

**Comment by w00fz** [comment]
See https://github.com/trilbymedia/grav-plugin-git-sync#known-issues-and-resolutions
