### ISSUE TITLE
When upgrading to PHP 8.0, git-sync throws PHP Fatal error:  Invalid opcode 117/2/0

### ISSUE THREAD

**Issue by GwynethLlewelyn** [trilbymedia/grav-plugin-git-sync#187]
Hi all!

I've been busily upgrading many of my sites to PHP 8.0, and, having learned that Grav 1.7 fully supports PHP 8.0, I did the upgrade without thinking twice.

It seems, however, that `git-sync` has some trouble:

```
PHP Fatal error:  Invalid opcode 117/2/0. in <GRAV_PATH>/user/plugins/git-sync/vendor/defuse/php-encryption/src/Core.php on line 412" while reading response header from upstream, client: <some IP address here>, server: <my server address here>, request: "POST /admin/plugins/git-sync HTTP/2.0",
````

Now, as far as I could search on Google or Bing about this particular issue, it seems to be common when upgrading PHP versions — especially when one's configuration uses [opcache](https://www.php.net/manual/en/book.opcache.php), [APC/APCu](https://www.php.net/manual/en/book.apcu.php), [Memcached](https://www.php.net/manual/en/book.memcached.php), or whatever fancy caching methods. I use them _all_, and even run `nginx` with Google's `pagespeed` library on top of everything — and, well, [Cloudflare](https://www.cloudflare.com/)...

In other words: because the compiled PHP scripts _may_ be slightly different between PHP versions (especially _major_ versions) — some opcodes having been made obsolete and dropped, others added, etc. — it is often likely for those levels of caching still contain some 'old' opcodes, thus the error. Strangely enough, in my case, they seem to persist not only when restarting `nginx` and `php8.0-fpm` (the latter accessed via a Unix socket), but even after a _reboot_ — so _something_ is maintaining persistence (I haven't tracked it down) at some point.

Note that this is not a 'bug' or 'error' of `git-sync` _per se_. I _have_ used the `grav` CLI to manually delete whatever caches `grav` is using (including the so-called 'compiled' directory); but I'm afraid that this will _not_ store low-level opcodes, and, thus, these won't be cached.

This issue naturally affects other platforms as well. [Here are some suggestions on how to force the opcode cache to be cleared in WordPress under Apache](https://www.saotn.org/wordpress-plugin-flush-php-opcache/). Naturally enough, such deep-level cache flushing techniques ought to get rid of whatever is persisting the cache.

I wonder if anyone has come across this issue and has tweaked something in `git-sync` so that it flushes all opcode caches whenever something gets upgraded.

Thanks in advance!

**Comment by w00fz** [comment]
Hi @GwynethLlewelyn, i haven’t tested php8.0 with gitsync yet but I’m glad to see someone is!

Usually that’s what I do myself, restart php/apache or nginx and that takes care of caches holding on too tightly.

One thing you could try is to go in `<GRAV_PATH>/user/plugins/git-sync`, remove (backup) the vendor folder and then run a `composer install —no-dev`. See if that helps.

**Comment by GwynethLlewelyn** [comment]
Whoops I'm so sorry; I had totally forgotten that I had opened this issue...!

Aye, it 'fixed by itself' — I don't remember doing anything, but there were Grav upgrades, OS upgrades, PHP upgrades, a few reboots... one of those must have fixed whatever the issue was, since I haven't seen it showing up ever again!

**Comment by w00fz** [comment]
No worries I figured as much, I was just doing some house cleaning with the new release out :)

Thanks for the update and glad it is sorted. 👍
