### ISSUE TITLE
Other Branches?

### ISSUE THREAD

**Issue by Umbyology** [trilbymedia/grav-plugin-git-sync#192]
Will this plugin work with other branches besides 'master'? ... I need to sync to/from a branch called 'work-in-progress' ... but I cannot get it to work. The branch 'work-in-progress' exists already.

Suggestions?

![Screen Shot 2021-02-25 at 2 36 03 PM](https://user-images.githubusercontent.com/22547499/109214179-20cc3700-7777-11eb-979d-baa34efa1a8a.png)

![Screen Shot 2021-02-25 at 2 18 57 PM](https://user-images.githubusercontent.com/22547499/109214197-288bdb80-7777-11eb-9d8c-06dcf31bb513.png)

**Comment by Umbyology** [comment]
Also, I have the auto-syncing set to off when I save and such, but I get the same error message, meaning it is still checking or trying to save to git anyway.

![Screen Shot 2021-02-25 at 7 39 14 PM](https://user-images.githubusercontent.com/22547499/109242823-73224d80-77a1-11eb-80f8-548ba5f6084f.png)

**Comment by Louson** [comment]
Same here using 'main' which is my default branch on gitlab.
Two following configs fail:
*  Local branch: master
   Remote branch: main
* Local branch: main
  Remote branch: main

While giving master/master works

**Comment by fm** [comment]
@Louson your issue may be related to #183, try the fix suggested there

**Comment by Louson** [comment]
It's related indeed

**Comment by w00fz** [comment]
See my comment https://github.com/trilbymedia/grav-plugin-git-sync/issues/183#issuecomment-821722119
