### ISSUE TITLE
git push is not working . I try all thinks

### ISSUE THREAD

**Issue by sureshjangid** [trilbymedia/grav-plugin-git-sync#195]
remote: Permission to WebAssembly/website.git denied to sureshjangid.
fatal: unable to access 'https://github.com/WebAssembly/website/': The requested URL returned error: 403

**Comment by fm** [comment]
That means you do not have access to push to that repo. Only members of that repo can push to that repo.

**Comment by sureshjangid** [comment]
> That means you do not have access to push to that repo. Only members of that repo can push to that repo.
Thank you, sir.
