### ISSUE TITLE
Multiple branches while syncing plugin's config

### ISSUE THREAD

**Issue by tbowan** [trilbymedia/grav-plugin-git-sync#197]
Hi all,

I have a git repository using multiple branches and each of them is served by a dedicated grav application.

Everything goes very well if I sync the pages and template directories. As I don't always remember all the setup done in one branch (and since it's not very clean to manuall copy the config directory between instances), I synced the plugin's directory (which work pretty well for all plugins except the git-sync one).

As the plugin config contains the local and remote branch name, every time I merge branch, this setting is overwritten and I must manually fix it in the grav's admin panel.

I thought I could use some .gitignore trick to ignore this specific plugin directory but saw #117.

Do you have some advices or best practices for such cases (having two grav, following different branches) ?

**Comment by w00fz** [comment]
I think what I need to do is to add an advanced textarea field where you can specify your gitignore, so that when GitSync does its thing, it will also include the custom entries.

Do you think that would help with the issue?

**Comment by tbowan** [comment]
Any way to tell the plugin to ignore its own config file will help me. A "true/false" to tell grav to read the official gitignore file, a "filename" field to tell grav where it will find a gitignore file or a textarea with a content formatted like a gitignore file (your proposal) wille help me.

The textarea has a good side effect because, I can still version a git-sync configuration in my repo :

* If it tells the plugin to ignore its configuration, the grav instance will stick on this specific branch (and configuration) after the first synchronization,
* Else, I can manually setup multiple instances, some of them with the ignore so that they follows their branches, some others without the ignore to follow the branch written in the config file in the repo.

Note that I don't need the second case (because merging setup files that contains branch names need to check the name after merge and re-commit to correct if it is the wrong one).

**Comment by w00fz** [comment]
I've got this implemented, going to be releasing it soon as v2.0.1. Thanks for this suggestion, going to be very useful.

<img width="575" alt="w00fz-2021-04-27_@_10 25 01@2x" src="https://user-images.githubusercontent.com/11734/116286043-a5b9d980-a743-11eb-95f3-f8aa41ec1358.png">

**Comment by tbowan** [comment]
I've just updated my plugin and put the git-sync config in the ignore list as follows :

![image](https://user-images.githubusercontent.com/11473294/116354856-4b7b5000-a7f9-11eb-9263-f803d2ba4d83.png)

After I saved the plugin state, It commited the setup modification in my repo :

![image](https://user-images.githubusercontent.com/11473294/116355042-91d0af00-a7f9-11eb-8b09-7aa792a00a89.png)

Since then, whatever I change in the configuration file, it's not updated (as expected) :

* Changes via the plugin are no more commited so the repo does not change,
* Changes in the repo (and pushed to origin), after the webhook call to the plugin, are not taken by the plugin so it remain in the same state.

Thanks a lot :-)

**Comment by w00fz** [comment]
Happy to hear this is working as you expected! 👍
