### ISSUE TITLE
fatal: unable to create thread: Resource temporarily unavailable fatal

### ISSUE THREAD

**Issue by JavaVista** [trilbymedia/grav-plugin-git-sync#198]
Ran the wizard fine and I am able to confirm that I can connect to github. However, I am getting the following error: 

The repository is private and I am trying to sync to my master branch. 

fatal: unable to create thread: Resource temporarily unavailable fatal: the remote end hung up unexpectedly send-pack: unexpected disconnect while reading sideband packet error: failed to push some refs to 'https://github.com/JavaVista/be-remarkable.git' fatal: the remote end hung up unexpectedly

**Comment by w00fz** [comment]
Hey @JavaVista, this is a git error. I did a quick googling and seems to be related to not enough memory available. People suggest to increase the memory with these commands:

```sh
git config --global pack.windowMemory "100m"
git config --global pack.packSizeLimit "100m"
```

Hope it helps.

**Comment by marcocevoli** [comment]
I'm on a Hostinger shared hosting server and was able to make it work with

```
windowMemory = 200m
packSizeLimit = 200m
```
HIH
