### ISSUE TITLE
repository.git/info/refs not found

### ISSUE THREAD

**Issue by sugarmaster** [trilbymedia/grav-plugin-git-sync#20]
Hi all.

I'm deploying git-sync for the first time and i'm having the next issue while configuring the plugin:

https://Sugarmaster:{password}@gitlab.com/Sugarmaster/mierdatime.git/info/refs
It seems to return a 401 - forbidden when I try to acess this folder.

When I configure and test connection I get this message:

"error: The requested URL returned error: 401 while accessing https://Sugarmaster:{password}@gitlab.com/Sugarmaster/mierdatime.git/info/refs fatal: HTTP request failed"

Any help?

**Comment by w00fz** [comment]
Sounds like you have the wrong credentials for gitlab. Try editing your username and password. Your user for instance, in quite sure is lowercase, I don't think upper cases are allowed.

**Comment by w00fz** [comment]
Did you manage to resolve this @sugarmaster ?

**Comment by sugarmaster** [comment]
I was unable to solve it even by changing it to lowercase. The credentials are ok because I used them to clone and commit to the repository. I also tried using bitbucket but i'm hitting the same wall.
I'm going to stick to updating my blog manually.

**Comment by w00fz** [comment]
Do you use 2 factory authentication?

**Comment by w00fz** [comment]
Also if you ebanble the logging in the plugin you can check in the logs/grav.log if there are any helpful errors

**Comment by sugarmaster** [comment]
What is 2 factory authentication? I'll try enabling the logs and trying again.

**Comment by sugarmaster** [comment]
Here goes my log info:
[2017-02-13 19:41:30] grav.NOTICE: gitsync[command]: LC_ALL=en_US.UTF-8 cd /home/mierdat1/public_html/user/ && git ls-remote "https://sugarmaster:{password}@gitlab.com/sugarmaster/mierdatime.git" 2>&1 [] []
[2017-02-13 19:41:32] grav.NOTICE: gitsync[output]: error: The requested URL returned error: 401 while accessing https://sugarmaster:{password}@gitlab.com/sugarmaster/mierdatime.git/info/refs  fatal: HTTP request failed [] []

**Comment by w00fz** [comment]
I really think the password is not correct, perhaps you have extra spaces?
The error says it fails to authenticate and retrieve data from gitlab.

From your terminal you could try the same command to see the response:

```
 cd /home/mierdat1/public_html/user/ && git ls-remote "https://sugarmaster:{password}@gitlab.com/sugarmaster/mierdatime.git"
```

Replace `{password}` with your actual password.

**Comment by sugarmaster** [comment]
Oh I think I found the issue: i have an old git version (1.7.1) installed in my shared hosting and i've seen this version is not supported by bitbucket  (https://confluence.atlassian.com/bitbucketserverkb/git-1-7-1-is-not-supported-by-bitbucket-server-779171467.html) and neither by bitbucket (https://gitlab.com/gitlab-org/gitlab-ce/issues/14758).
With github it works just perfect so i'll stick with it I think.

**Comment by w00fz** [comment]
Interesting. Nice to see you sorted and thanks for the details. 

`
