### ISSUE TITLE
how can I create an access token

### ISSUE THREAD

**Issue by TabbasamMalik** [trilbymedia/grav-plugin-git-sync#204]
how can I create an access token

_Originally posted by @ghost in https://github.com/trilbymedia/grav-plugin-git-sync/issues/39#issuecomment-469790240_

https://github.com/settings/tokens/new?description=Android%20Studio%20GitHub%20integration%20plugin&scopes=repo%2Cgist%2Cread%3Aorg

**Comment by w00fz** [comment]
Is this a question? https://github.com/settings/tokens/new is indeed the way of doing it…

**Comment by futurestar425** [comment]
remote: Your account is suspended. Please visit https://support.github.com for more information.
fatal: unable to access 'https://github.com/topexpert123/XFI-DApp.git/': The requested URL returned error: 403
I have this error.
how to fix?
