### ISSUE TITLE
Synced folders are supposed to be at root level of the repository

### ISSUE THREAD

**Issue by sherpadawan** [trilbymedia/grav-plugin-git-sync#215]
I have just tried Git Sync plugin, on a project in which web root is called htdocs (gandi hosting), then pages, config, themes etc.. forlders were created above htdocs...
then I tried to delete all those extra directories which ere actually not served (because not under htdocs), and Git Sync deleted all my project files (pages, plugin etc...), all my personnal content disappeard, I rolled back and deactiate the plugin.
I don't understand how it works.

**Comment by hughbris** [comment]
The plugin is designed to sync a repo under `user`. It's in the README, but should possibly be made more prominent:

> Synchronize any folder under user (pages, themes, config)

I didn't write the plugin but I hope that helps.
