### ISSUE TITLE
fatal: unable to create thread: Resource temporarily unavailable fatal: the remote end hung up unexpectedly send-pack: unexpected disconnect while reading sideband packet fatal: the remote end hung up unexpectedly error: failed to push some refs to 'https://gitlab.com/repo/projectname.git'

### ISSUE THREAD

**Issue by ambein** [trilbymedia/grav-plugin-git-sync#217]
Using gitsync with gitlab account with a https://github.com/hibbitts-design /
[grav-skeleton-course-hub](https://github.com/hibbitts-design/grav-skeleton-course-hub)... followed directions via backend admin wizard... final sync results in:

"fatal: unable to create thread: Resource temporarily unavailable fatal: the remote end hung up unexpectedly send-pack: unexpected disconnect while reading sideband packet fatal: the remote end hung up unexpectedly error: failed to push some refs to 'https://gitlab.com/repo/projectname.git'"

No updating of repo...

Tried gitsync with another of th ehibbitts-design skeletons on another site, to no avail... (just crashed the site)...

**Comment by mahagr** [comment]
It looks like there's an issue with connecting to gitlab.
