### ISSUE TITLE
Unable to sync with GitLab Repository

### ISSUE THREAD

**Issue by petarmihaylov** [trilbymedia/grav-plugin-git-sync#24]
Hello there!

This is likely an issue between the keyboard and the chair and not with Git Sync itself, but I can't seem to figure out what I am missing.

I have installed Git Sync on a local copy and when I go through the wizard I paste: 
```https://gitlab.com/studio350-private/studio350.com.git```

However, I get an error message that says:
```fatal: repository 'https://www.studio350.com/studio350-private/studio350.com.git/' not found```

Why is it looking for the repository at ```https://www.studio350.com``` when I am entering ```https://gitlab.com/```?

What is even more interesting is that I am running the wizard from the local copy which is at ```studio350.local```. I guess the plugin is pulling the actual site URL from somewhere in the configuration files, but I can't seem to figure out from where.

I get the same error when I try to configure the plugin from the actual website at ```studio350.com```.

The one thing I can think of that can be causing this is that I don't host the website on GitLab in either of these two cases. However, in the introductory video (and the Wizard instructions) only says that you hat o have a repository with one commit in it.

Any help will be much appreciated.

Thank you and have a blessed day!

Respectfully,

Petar

**Comment by w00fz** [comment]
That is strange! Have a look at your user/config/plugins/git-sync.yaml as well as your user/.git/config.
Is it showing www.studio350.com in any of the two?

// Djamil Legato // From iPhone //

**Comment by petarmihaylov** [comment]
Neither shows mention studio350.com.

```
user/.git/config:

[remote "origin"]
	url = https://[login_name]:[password]@gitlab.com/studio350-private/gitsync-test.git
```
The above has the actual (correct) login and password. I replaced those for obvious reasons.

```
user/config/plugins/git-sync.yaml:
repository: 'https://gitlab.com/studio350-private/gitsync-test.git'
```
![Error Message Screenshot](http://i.imgur.com/ezJG0Ck.png)

Thank you much! Any other ideas? :)

**Comment by w00fz** [comment]
Oh yes don't use the email as login, only username.

**Comment by petarmihaylov** [comment]
Like I said from the beginning - a problem between the keyboard and the chair!

Entering the Username instead of the e-mail fixed it!

When I was going through the wizard, I read 'Username of email', when in fact it says 'Username, not email'.

I think it may be a good idea to somehow emphasize this for people like me who apparently can't read! 👍

**Comment by w00fz** [comment]
Will made that more clear. Any suggestion or PR more than welcome.

Glad it was an easy resolution anyway!

**Comment by jjunho** [comment]
I'm having a similar problem. I can see in the popup that opens with the error that the special characters in my password are escaped with backslash and numbers instead.
