### ISSUE TITLE
Default Git service for first-run of wizard 

### ISSUE THREAD

**Issue by paulhibbitts** [trilbymedia/grav-plugin-git-sync#26]
A very minor issue... when the wizard is run for the first time the Other (Git) choice seems to still be selected by default.

I would think that no Git service is selected initially (if I recall correctly this was the way it used to be...), and that either the Next button is disabled until a choice is made or perhaps a message is displayed telling the user they must first select a Git service before they continue.

Thanks for considering this suggestion.
Paul

**Comment by erlepereira** [comment]
hey just saw this, its a quick fix... just sorting out some issues on my forked repo and will send a pull request

**Comment by w00fz** [comment]
Thank you @erlepereira
