### ISSUE TITLE
plugin (wizard) doesn't run if admin route isn't /admin

### ISSUE THREAD

**Issue by violoncelloch** [trilbymedia/grav-plugin-git-sync#27]
I can't start the initial wizard
clicking the wizard button does nothing, expect from adding a # to the url...

Grav v1.1.17 - Admin v1.2.14 - GitSync v1.0.3

**Comment by jones4410** [comment]
following your tutorial video I tried to set it up manually but it even won't sync...
what am I doing wrong or what is the problem of my grav setup?

**Comment by jones4410** [comment]
Ok I've just set up a new grav installation with another theme and the plugin works perfectly... I'm now trying to figure out the problem of my main grav setup...

**Comment by jones4410** [comment]
just found the problem: if you set e custom route for the admin panel (something like `example.com/gravconfig` instead of `example.com/admin`) the plugin or at least the wizard doesn't run. I think this is a bug...?
would be nice if you fixed this!

**Comment by JLehtinen** [comment]
Replicated. The plugin works with custom routes after setup, so workaround is to temporarily change the admin route to default `/admin` to run the wizard, then change it to what you want.

**Comment by w00fz** [comment]
Oh that's a good catch! I'll look into this.

**Comment by w00fz** [comment]
Fixed with #77
