### ISSUE TITLE
[doc] Change instructions for bitbucket

### ISSUE THREAD

**Issue by paulmassen** [trilbymedia/grav-plugin-git-sync#3]
Good job on this excellent plugin.

One thing I noticed, is that if used with a bitbucket account, you have to slightly edit the pasted https url in order for the plugin to work.
It's just a detail but it might be worth adding it to the doc
Example:
Pasted url from bitbucket: https://myusername@bitbucket.org/myusername/myrepo.git
Working url: https://bitbucket.org/myusername/myrepo.git

Congrats again!

**Comment by w00fz** [comment]
Thank you! I will look into making this more clear
