### ISSUE TITLE
doesn't work in a multisite env

### ISSUE THREAD

**Issue by tourtools** [trilbymedia/grav-plugin-git-sync#33]
when trying to sync or when modifying pages it logs:

`grav.NOTICE: gitsync[command]: LC_ALL=en_US.UTF-8 cd  /var/www/.../user/ && git status 2>&1 [] []`
`grav.NOTICE: gitsync[output]: # On branch master nothing to commit (working directory clean) [] []`

there's a way to tell the plugin, maybe through its config file git-sync.yaml, in which path has to work?

**Comment by tourtools** [comment]
maybe through the definition of a "git-sync" stream in the /setup.php?

**Comment by w00fz** [comment]
I'm not sure I understand the issue, the log looks correct to me.
Gitsync is trying to sync your user folder, it's setup to ignore everything but pages, sees pages are up to date and doesn't need to pull/push

**Comment by tourtools** [comment]
it refers to a multisite installation, 
the gitsync is triggered from a site in the dir /user/sites/foo.bar, where the plugin is installed, 
but the git status is executed on the /user/ root

**Comment by Just-Insane** [comment]
This still appears to be an issue. When in a multisite environment, one has to copy the plugin files into the user/sites/<site>/plugins folder (from the <grav_root>/plugins folder). 

On top of that, when using the wizard, it does not seem to automatically create the git repository for the current site. This prevents the plugin from being used in a multisite Grav setup.
