### ISSUE TITLE
Repos collision

### ISSUE THREAD

**Issue by tmk1** [trilbymedia/grav-plugin-git-sync#34]
Plugin works great but by default it syncs only /user/pages directory.

I've decided to use plugin for the pages only and second private repo for the rest of the folders (both core and other user folders) - and it's impossible without extra hacking, because - as we can read in 
https://github.com/trilbymedia/grav-plugin-git-sync/issues/21- repo of the plugin is created for the whole /user directory.

I suggest to:
- setup plugin repo only on /user/pages directory (I'd prefer this one :) )
or
- add the missing frontend options to choose all (or some) user folders.

**Comment by w00fz** [comment]
You can add other user folders from the yaml configuration as explained in #21. It really isn't hacking, it's just a configuration field that hasn't a visual UI in the admin.
Nothing wrong with changing that from the file.

**Comment by tmk1** [comment]
1) It's not documented - user needs to dig through Issues to find info how to do it.
2) _On branch master Changes not staged for commit: modified: config/site.yaml no changes added to commit_  - that's the info that I get when trying to use Synchronize button - so the functionality is not so useful at the moment
3) As it is written in #21 - there is no way to auto-sync some folders e.g. themes or plugins so I think it makes more sense to have it in separate repo - one - that user knows - it must be managed manually OR there should be some button on the Dashboard to invoke add . and commit/sync actions for the whole user directory.

**Comment by karfau** [comment]
@tmk1 In case you want to experiment with the setup you described (which is what I'm using as well) you can have a look at [my fork](https://github.com/karfau/grav-plugin-git-sync).

The changes I made: https://github.com/trilbymedia/grav-plugin-git-sync/compare/develop...karfau:experiment/pages-folder-contains-repo 

I tested it as far as my configuration is concerned and it works, even with the wizard.  
But so far I always modified the git config after the wizard for customization, so I'm not totally sure it works out of the box. 

Feel free to contact me (e.g. Grav Slack private message) with any findings.
