### ISSUE TITLE
Causing OpenSSL errors on localhost using MAMP PRO

### ISSUE THREAD

**Issue by duksh** [trilbymedia/grav-plugin-git-sync#36]
I am using MAMP PRO v3.5 on MAC to install the grav git-sync plugin for development testing purpose. The error am getting is:
-------------
Server Error
Sorry, something went terribly wrong!

0 - Cipher method not supported. This is normally caused by an outdated version of OpenSSL (and/or OpenSSL compiled for FIPS compliance). Please upgrade to a newer version of OpenSSL that supports aes-256-ctr to use this library.

--------------
The grav log file is attached
[grav-log.txt](https://github.com/trilbymedia/grav-plugin-git-sync/files/896068/grav-log.txt)

**Comment by w00fz** [comment]
I actually never seen this error before, have you tried changing the PHP version to 5.6 or 7.0?
Also, do you have all the MAMP SSL libraries enabled?

**Comment by duksh** [comment]
Hi @w00fz yes my MAMP SSL Module was enable + PHP version was set to v7

**Comment by w00fz** [comment]
Is this still an issue? It seems like you have everything in order for it to work. That error looks strange, I have never seen it before.

What macOS version are you running? By the sound of it it just seems like you have some outdated openssl libraries that need to be handed at OS level.

**Comment by thekenshow** [comment]
FWIW, MacOS Sierra latest (10.12.6) with MAMP Pro 3 was generating this error. Upgrading to MAMP Pro 4 resolved the issue.
