### ISSUE TITLE
unable to hide pages

### ISSUE THREAD

**Issue by Raboo** [trilbymedia/grav-plugin-git-sync#37]
When I try to hide a page (i.e. make it non-visible) it get this error message:

```
warning: You ran 'git add' with neither '-A (--all)' or '--ignore-removal', whose behaviour will change in Git 2.0 with respect to paths you removed. Paths like 'pages/02.about/default.md' that are removed from your working tree are ignored with this version of Git. * 'git add --ignore-removal ', which is the current default, ignores paths you removed from your working tree. * 'git add --all ' will let you also record the removals. Run 'git status' to check the paths you removed from your working tree. The following paths are ignored by one of your .gitignore files: themes Use -f if you really want to add them. fatal: no files added
```

And sync is b0rked.

**Comment by Raboo** [comment]
additional info
```
# git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    pages/02.about/default.md
	modified:   pages/03.login/external.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pages/02.home/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by Raboo** [comment]
Sorry, I now realized that it must be when I renamed about to home. Not when i set it as non-visible.

**Comment by paulhibbitts** [comment]
Hi @Raboo , I've tried to duplicate your issue but no luck so far. My tests have involved renaming a page via Admin and also via direct file edit.

Might there be any more info you could share that led to the Git Sync error?

**Comment by Raboo** [comment]
Could it have to do with my git version?
git version 1.9.1

**Comment by paulhibbitts** [comment]
Thanks for the info. That should be ok, as Git Sync was tested with 1.7.1 (if I remember correctly) as the minimum required version. Have you tried again with a fresh Grav install/repo?

**Comment by w00fz** [comment]
Hello Raboo,
can you try editing the line 155 of `GitSync.php` file under `classes/` folder. Instead of `1.8.1.4` change the version to `1.9.1`.

Then try again and see if that change helps.

**Comment by Raboo** [comment]
@w00fz I did that.
That warning disappeared, but it doesn't delete the old folder/files.

Created a page called rename, saved. renamed to rename2.
It pushed the new rename2 to git. But it didn't do a git rm and push.

```
# git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    ../../pages/01.blog/rename/item.md

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by Raboo** [comment]
I'm not experiencing the same issue any more with the latest version of this plugin. closing..
