### ISSUE TITLE
Support for git submodules

### ISSUE THREAD

**Issue by thgh** [trilbymedia/grav-plugin-git-sync#40]
Current setup: `/user` is a git repo which contains `themes/immo` which is a git submodule.

When I update the theme (submodule) on my local computer and commit the changes in the user repo and push them, the theme folder is marked as modified on the online server. The solution is to run `git submodule update --recursive`, but it kind of defeats the purpose of this plugin.

How can I let grav run that command after every pull of the user repo?  
What are the best practices for creating reusable themes?

**Comment by w00fz** [comment]
Hello,
GitSync comes with an event system that allows for 3rd party plugins/themes to hook up into it.

The events are:
1. `onGitSyncBeforeSynchronize`
2. `onGitSyncAfterSynchronize`
3. `onGitSyncBeforeReset`
4. `onGitSyncAfterReset`

What I would do in your case is to [create a Plugin](https://learn.getgrav.org/plugins/plugin-tutorial) that hooks into the `onGitSyncAfterSynchronize` and then performs the shell command for updating the modules.
This way it will always be automated and happening every time git syncs performs a synchronization.

Hope it helps!
