### ISSUE TITLE
Reminder needed to avoid using Grav ACLs with public repos

### ISSUE THREAD

**Issue by J-Rey** [trilbymedia/grav-plugin-git-sync#41]
A reminder/warning should be included in the README, Wizard or both that if using access rules with Grav to restrict content then only a _private_ git repository hosting service should be used to avoid exposing the same content to the public.

I know it should be common sense but could easily be overlooked/forgotten if new access rules are setup (like I'm in the middle of) or sync is changed to a public repo after the initial implementation.

**Comment by w00fz** [comment]
This is a good idea. Would you like to add this warning in the README in the form of a PR? I would gladly merge that in.
