### ISSUE TITLE
Cannot sync to a github branch

### ISSUE THREAD

**Issue by Dominance** [trilbymedia/grav-plugin-git-sync#42]
So may be clueless here but cannot for the life of me figure out how to set up the plugin to only sync to a separate branch from master. in my case "webdev" and not "master" regardless of the why, is this possible?

**Comment by jaygorrell** [comment]
Hitting same thing here

**Comment by w00fz** [comment]
In the plugin settings there is a section where you can change the branch.

You want to change that `master` to `webdev` and you should be good to go.

![plugin git sync grav 2017-05-15 13-11-42](https://cloud.githubusercontent.com/assets/11734/26077181/104f2de0-3970-11e7-9d1b-f507a0b038b8.png)

**Comment by denniswebb** [comment]
Changing that had no effect on our testing.  We changed this setting after originally setting it up with the 2 branches matching.  I added the above PR to specify the local branch specified to the `git push` command to make sure it obeys configuration changes to the remote branch no matter what remote branch it's tracking.

**Comment by jaygorrell** [comment]
Yeah, it doesn't look like `branch` is ever pulled with getConfig(), only getRemote(). I don't think that local branch name actually gets used without #48
