### ISSUE TITLE
"Your system does not have a secure random number generator"

### ISSUE THREAD

**Issue by thomasporhel** [trilbymedia/grav-plugin-git-sync#44]
When clicking on "save" at step 3 of the wizard I have the error:
"Your system does not have a secure random number generator"
(see attached screenshot)

And in Github the payload URL returns a 404 error apparently.

![screen shot 2017-05-06 at 10 49 13](https://cloud.githubusercontent.com/assets/22839288/25771156/d69ccb8e-3249-11e7-9008-e1988f93a6e5.png)

Any ideas how to fix this?

**Comment by OleVik** [comment]
This means that PHP cannot use the Defuse-library, possibly because of some permissions-issue. What PHP version are you using? With PHP 7.0 or higher it should use `random_bytes`.

**Comment by thomasporhel** [comment]
Thanks OleVik! Now that PHP 7.0 is installed on the server it works perfectly (-:
