### ISSUE TITLE
"The Git-Sync plugin requires the git binary to be installed and accessible in order to work." 

### ISSUE THREAD

**Issue by justs** [trilbymedia/grav-plugin-git-sync#46]
NEVERMIND, it was, in fact, the Binary Path. I was assuming the prefilled text was adequate. Retyping that pre populated text and saving ha resolved the issue. Sorry for taking up space here.

This is such an exciting plug-in! I wish I could make us of it, but no matter what I have tried, I can't seem to get it to work. I am running the Grav site on a QNAP 453A NAS with QTS 4.3.3 and QGit 2.1.0 installed from [here](https://forum.qnap.com/viewtopic.php?f=301&t=97220). While the site works flawlessly, the Git-Sync doesn't play well :-( Get the error message, _The Git-Sync plugin requires the git binary to be installed and accessible in order to work._ 

I am guessing it is related to the _Git Binary Path_ field.

When I press the Synchronize button in the plug-in manager, I get the toast message, _GitSync has successfully synchronized with the repository._ but no changes are actually synced to GitHub.

![image](https://cloud.githubusercontent.com/assets/550659/25962386/c3e66500-363a-11e7-9617-321248a54f14.png)

When I hit the Wizard or Save buttons in the plug-in manager, I get a pop-up with _The Git-Sync plugin requires the git binary to be installed and accessible in order to work._

![image](https://cloud.githubusercontent.com/assets/550659/25962400/d2256026-363a-11e7-8441-19a124729235.png)

I'm very green when it comes to git and working with command lines so it is most likely something I am doing wrong. Any ideas?

**Comment by jbzcooper** [comment]
Same issue but on Windows. Entered the git binary path: C:\Program Files\Git\bin\git.exe but still getting error. Thoughts?

**Comment by Arsjok** [comment]
Im getting this problem too same folder '/usr/bin/git'
