### ISSUE TITLE
when publishing grav to heroku git sync credentials (auth token) lost 

### ISSUE THREAD

**Issue by lpaulger** [trilbymedia/grav-plugin-git-sync#47]
I have a grav website managed privately in github and I've ensured that "user/config/plugins/git-sync.yaml" is stored properly with password property.

when I publish to heroku though the content is lost and when I go to the "git-sync" plugin, all the credentials exist but the content wont sync. The content only syncs after I re-enter the auth token and save.

How can I get the content to sync properly when I publish a new version of my grav site?

**Comment by w00fz** [comment]
Can you verify that the version on heroku has still the same configuration settings you applied for the GitSync plugin?
This should just works but by the sound of it it looks like the configuration gets reset.

**Comment by lpaulger** [comment]
I can verify that the git-sync config credentials are the same. They are updated correctly when I run locally, and I commit the entire user/config/plugins/git-sync.yaml which has the correct repository, user and password (presumably). I'm not fond of keeping these credentials in the yaml file bu this is at least a private repo.

I've also tried to setup the git-sync as a post install 
```
        "post-install-cmd": [
          "bin/plugin git-sync sync"
        ],
```
but I encountered the following error when pushing to heroku
```
Synchronizing with https://github.com/zenloopGmbH/grav-sync.git
                                                                              
[RuntimeException]                                                          
fatal: Not a git repository (or any parent up to mount point /tmp)          
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).  
```

**Comment by lpaulger** [comment]
I'll close this ticket as a duplicate of https://github.com/trilbymedia/grav-plugin-git-sync/issues/13, I see that the password actually isn't lost but stored securely. 

and that the automatic git-sync feature isn't supported yet. 

Thanks
