### ISSUE TITLE
Avoid pathcing the remote URL for doing authentication

### ISSUE THREAD

**Issue by karfau** [trilbymedia/grav-plugin-git-sync#53]
### Context/Assuptions

As far as I understood the code, the way this plugin currently does authentication for `git` is as follows:  

1. patch `repository` from configuration to contain username and decrypted password or token (as in `https://user:pass@github.com/user/repo.git`)
2. use `patchedURL` to modify the URL of the configured remote by calling `git remote set-url {remote} {patchedUrl}`
3. do what needs to be done for synchronizing
4. set the URL of the configured remote back to `repository` from config by calling `git remote set-url {remote} {repository}`

### Problem(s)

- Makes it hard to work with your plugin and command line at the same time, because it overwrites whatever was set as the remote URL (e.g. SSH URL) which means I need to provide the password every time in the console or set up stuff like `SSH_ASKPASS` or `GIT_ASKPASS`.
- It stores the decrypted password or token to the disk. :-1: (don't get me started on using this plugin with shared hosting.)
- In case the script fails (e.g. because any git command returns with an exit code other then 0) the value is not returned to its original state. until this is fixed, you can do anything that password or token allows from the shell.
- (just for the completeness, as I don't know any solution to this. Not even the solution that I'm suggesting prevents it.)  
There are several shell commands executed using PHP's [exec](http://php.net/manual/en/function.exec.php) contain the decrypted password. You did a good job in providing logging that covers it, so that isn't part of the logging provided by the plugin, but I'm ot sure about the chances of information leak though shell commands executed this way.

### Suggested solution(s)

**A)** put some effort into **always** return the state to its original state. (not sure how far we can get, but also willing to work on this if preferred.)

**B)** use the `GIT_ASKPASS` [approach](https://git-scm.com/docs/gitcredentials.html#_requesting_credentials) to provide credentials.
I did some testing and [could make it work basically](https://github.com/karfau/grav-plugin-git-sync/blob/experiment/pages-folder-contains-repo/cli/GIT_ASKPASS.md).  
As I said the solution I have in mind doesn't solve the last problem, but all the other ones.

I'm happy to provide a PR for it, but only in case the team behind this plugin cares enough to review it.

I hope I didn't offend anybody, I really like the approach that this plugin takes and want to contribute to make it even more awesome.

Best Christian

**Comment by w00fz** [comment]
First of all, sorry if I just only reply to this and thank you for the very well composed issue, all I can say is that you have only good points here and I like where your head is going with GIT_ASKPASS.

Even though I do mask the password pretty much everywhere that could be leaked, I myself don't really like using my main password.

What I currently do myself and suggest others to do as well, is to enable 2FA, create an Auth Token and log in with that as password, rather than the actual password account.

I know it's not what you are suggesting GitSync should do, but at least it adds an extra layer of security with 2FA as well as preventing from exposing your own password and instead using a Token that can be discarded anytime.

I would like to think more about your ideas and approaches and know if you have experimented more since then. Right now I have a huge 2.0.0 pending release but I don't feel like venturing into the authentication/GIT_ASKPASS.

**Comment by karfau** [comment]
Thx for the reply.
As you might have noticed I was using my slightly modified fork for a while.
In the mean time I'm not using git-sync plugin anymore, mainly because of the issues I reported.
Instead I wrote the following shell script and run it as a cron job:
```
#!/usr/bin/env bash
set -xe
cd "$(dirname "$0")/.."
cd user/pages/
pwd
if [[ -d .git ]] ; then
  : "check for local changes to be commited"
  if ! [[ -z $(git status --porcelain) ]] ; then
    git add .
    git commit -m "commit by $(basename "$0")"
  fi

  : "fetch and attempt rebase, abort rebase and exit when there are conflicts"
  git pull --rebase || (git rebase --abort && exit 666)

  : "check for things that need to be pushed"
  if ! [[ -z $(git status --porcelain --branch) ]] ; then
    git push
  fi
fi
```
Im running this with [`cron-tab-runner`](https://gist.github.com/karfau/053acab10ecea3c4d0f9ec858a6b35b2#ctr-crontab-runner) so I get mails when something fails.

I "solved" the auth problem by having an extra ssh key on that server that I added to my github settings.

So in a way it "works for me" by not using git-sync.

Best regards

**Comment by w00fz** [comment]
Thanks for sharing  @karfau.
You should check out Grav’s built-in scheduler in Grav 1.6 if you haven’t already. 🙂

**Comment by karfau** [comment]
I'm still using 1.3, not sure when I will find time to update. My plan goes towards minimizing the parts of grav I'm using. One reason to upgrade would be  proper rest API.
