### ISSUE TITLE
Setup wizard hanging on Step 2 and Step 3

### ISSUE THREAD

**Issue by kescobo** [trilbymedia/grav-plugin-git-sync#55]
I'm attempting to setup gitsync for [a website](http://nequals.me) on reclaim hosting. In case it matters, I'm using a [skeleton template from here](https://github.com/hibbitts-design/grav-skeleton-eportfolio-blog). I'm using 2FA, but I've got the application key set up, and I'm using that to sign in (I've got an empty repo [here](https://github.com/kescobo/nequals.me)). 

Both on step 2 of the setup wizard, when I hit "test connection" and on step 3 when I try to complete the installation, nothing happens (after step 3 my browser says "waiting for nequals.me). 

Also after both steps, I can see that there are processes running in cPanel (1 seems to get triggered by the "test connection" step, and 2 seem to be triggered by trying to complete the setup). These processes hang indefinitely, and if I refresh and try again, new processes get piled on. 

The only place (I think) I've deviated from the tutorials is that the repo I set up is currently public - is it completely necessary to have a private repo? I'd like it if the source files are accessible, though obviously if there's anything stored that's a security concern it would be worth knowing.

**Comment by paulhibbitts** [comment]
Hi @kescobo , both public and private repositories are supported so that should be ok. Have you tried to do a test setup without 2FA? I have a lot of Reclaim installs running with Git Sync, but I've never used 2FA myself.

**Comment by kescobo** [comment]
Hi @paulhibbitts Thanks - I did watch that video and followed those steps.

I haven't tried without 2FA. I remember it being somewhat onerous to set up and didn't want to muck with the settings if there was an alternative, but if that would be a useful test to figure out what's wrong, I'm happy to give it a go.

**Comment by kescobo** [comment]
Update: Just disabled 2FA and attempted to do the sign-in with just username and password and I've got the same issue.

**Comment by kescobo** [comment]
I just noticed I'm unable to navigate around in the Grav dashboard as well - when I click somewhere else, it says I've got unsaved changes, I click "continue" and the site hangs. Looking back in cPanel, these actions have also spawned additional processes that won't terminate.

**Comment by paulhibbitts** [comment]
Hmm... this might be an issue on the server side of things. Perhaps open a support ticket with Reclaim (I remember I had to get the number of supported Processes increased at some point)? Depending on the result might as well try 2FA out of the gate as well.

BTW, I am often in the Grav Slack room if you have questions, etc. about the ePortfolio Blog: https://getgrav.org/slack

**Comment by kescobo** [comment]
Oddly, without me changing anything (that I'm aware of), it now seems to be working. I also reenabled 2FA, and that's working as well. I'm very confused, but oh well. 

I still have 6 entry processes running on the server that were spawned when I was having issues though, so it's clearly not entirely imaginary. I'll close this issue for now without knowing the cause/solution.

**Comment by paulhibbitts** [comment]
Great to hear that you got it working! Perhaps it was a temporary server issue?

**Comment by kescobo** [comment]
@paulhibbitts Maybe, though I had a support ticket opened with reclaim about it as well and they didn't mention anything that might be related. I think it will have to remain a mystery :-)
