### ISSUE TITLE
Admin panel randomly logs out with git-sync installed

### ISSUE THREAD

**Issue by nthnwlkr** [trilbymedia/grav-plugin-git-sync#59]
With the git-sync plugin installed on the webserver, Grav admin will often be logged out. Logging out usually occurs either when the plugin's configuration panel is saved, or when an edit to a site page is saved (e.g. editing the markdown). It has also happened when navigating to the plugins page through the admin panel sidebar navigation, prompting me to suspect it isn't related to any one page.

The result is that any changes made during that session are discarded. For example, a markdown edit will be reflected on the site, but when the logout occurs after a subsequent edit is saved, both changes are removed and the site is returned to the state prior to the editing session. 

When I uninstall the plugin through the admin panel, the issue with random logging out appears to no longer occur, at least not during the time I have tested it (during the same time with the plugin installed it would have occurred roughly 3 or 4 times). 

It's quite possibly user error, but I have really no idea how I could have suddenly caused this issue. 

**Potentially relevant:**

- Each time I visit the git-sync plugin page in the admin panel, the wizard is launched and my GitHub password never seems to be stored. Not sure if this is expected behaviour. 
- The issue has only begun to occur recently, the admin panel has been running for a few months with no issues.
- This problem occurred with both v2.3.1 and v2.3.2 of the Grav "Login" plugin
- The automatic commits that are pushed to the GitHub repo contain only the relevant edits from the pages folder, however the `"merge branch 'my-branchname' of 'my-repo-url' "` commit not only commits a copy of the entire repo, the commit also appears to occur on none of my repo's branches, I think they're somehow becoming "detached HEADs".

**Comment by w00fz** [comment]
I dont think this is related to GitSync. Did this issue go away with the latest and greatest of grav/admin/login/form?

**Comment by w00fz** [comment]
Feel free to reopen if this is still an issue.
