### ISSUE TITLE
Git merge error when updating a page

### ISSUE THREAD

**Issue by deadlyhifi** [trilbymedia/grav-plugin-git-sync#6]
I'm getting the following error when saving a page within the Grav admin.

```
From https://here.org/there/everywhere * branch master -> FETCH_HEAD error: The following untracked working tree files would be overwritten by merge: plugins/admin/blueprints/admin/pages/modular_new.yaml plugins/admin/blueprints/admin/pages/modular_raw.yaml plugins/admin/blueprints/admin/pages/move.yaml plugins/admin/blueprints/admin/pages/new.yaml plugins/admin/blueprints/admin/pages/new_folder.yaml plugins/admin/blueprints/admin/pages/raw.yaml plugins/admin/pages/admin/ajax.md plugins/admin/pages/admin/backup.md plugins/admin/pages/admin/cache.md plugins/admin/pages/admin/config.md plugins/admin/pages/admin/dashboard.md plugins/admin/pages/admin/denied.md plugins/admin/pages/admin/feed.md plugins/admin/pages/admin/forgot.md plugins/admin/pages/admin/info.md plugins/admin/pages/admin/installer.md plugins/admin/pages/admin/login.md plugins/admin/pages/admin/logout.md plugins/admin/pages/admin/media.md plugins/admin/pages/admin/notifications.md plugins/admin/pages/admin/pages-filter.md plugins/admin/pages/admin/pages.md plugins/admin/pages/admin/plugins.md plugins/admin/pages/admin/register.md plugins/admin/pages/admin/reset.md plugins/admin/pages/admin/site.md plugins/admin/pages/admin/statistics.md plugins/admin/pages/admin/system.md plugins/admin/pages/admin/themes.md plugins/admin/pages/admin/update.md plugins/admin/pages/admin/user.md plugins/admin/themes/grav/app/pages/filter.js plugins/admin/themes/grav/app/pages/index.js plugins/admin/themes/grav/app/pages/page/add.js plugins/admin/themes/grav/app/pages/page/delete.js plugins/admin/themes/grav/app/pages/page/disable-buttons.js plugins/admin/themes/grav/app/pages/page/index.js plugins/admin/themes/grav/app/pages/page/media.js plugins/admin/themes/grav/app/pages/page/move.js plugins/admin/themes/grav/app/pages/page/multilang.js plugins/admin/themes/grav/app/pages/tree.js plugins/admin/themes/grav/templates/forms/fields/pages/pages.html.twig plugins/error/pages/error.md plugins/login/pages/forgot.md plugins/login/pages/login.md plugins/login/pages/register.md plugins/login/pages/reset.md Please move or remove them before you can merge. Aborting
```

I've copied the plugins folder from my server and pushed the changes to make sure it matches what I have locally - there were some minor differences but none in the admin, error, or login plugins.

Copying `plugins/admin/blueprints/admin/pages/modular_new.yaml` specifically from the server and comparing with local shows no difference in the file.

Not sure what the issue is, can you shed any light on it?

**Comment by deadlyhifi** [comment]
git version 1.9.1

I changed repos, but I deleted the .git folder on the server within `public/user`, then went through the whole setup process again within the Git-Sync plugin.

I'll do some more investigation and report back my findings. I'll probably just delete all of `user`, re-upload it, and then set up git-sync again. Thanks for your response.

**Comment by w00fz** [comment]
I can see this being a problem, GitSync is capable of discarding un-matching histories between repositories but if the structure is very different a merge conflict is unavoidable. 
Probably deleting the whole user folder is the best way to go, alternatively you can also try clicking the `Reset Local Copy` button after you see the merge error, that should reset your local to fully match the new repository you added.

**Comment by w00fz** [comment]
I'm going to close the issue and considered it resolved, feel free to reopen otherwise.
