### ISSUE TITLE
Keep getting "The GitSync plugin requires the binary to be installed and accessible in order to work."

### ISSUE THREAD

**Issue by drnasin** [trilbymedia/grav-plugin-git-sync#60]
Git is installed, accessible as "git", works like a charm in terminal...what could be wrong?
Sync button apparently also works. It's just the wizard that cannot be started for some reason. Tried clearing cache, re-installing....nothing helps....any suggestions?

**Comment by w00fz** [comment]
Checkout where exactly is the binary located and in the admin, use that binary location under Advanced Settings -> Git Binary Path

ie, `/usr/bin/git`

**Comment by drnasin** [comment]
hey w00fz , thank you! I made some progress but I hit a road block again :/ I want to make this work as I think this will be really good for my customers. Now that I've set up everything I get "warning: no common commits fatal: unable to create thread: Resource temporarily unavailable fatal: index-pack failed"

**Comment by drnasin** [comment]
got it! :) love it! thanks @w00fz 
and big thanks to the sponsors for letting us use it!

**Comment by drnasin** [comment]
btw @w00fz  could you mention in the readme file that the "pages" folder will be moved to root and the real one will be .gitignored. Took me longer than it should to get that :/

**Comment by drnasin** [comment]
@w00fz Djamil do you have private contact I can use? Would like to ask you something. Just to make clear.. I'm not selling or offering anyhting nor I need anything debugged :p

**Comment by karfau** [comment]
@drnasin in case the pages folder is put into the root of your repo, your repo structure is not configured as expected by got sync plugin.
There are some open issues with more information on this topic.

To get in touch with any developer you can use the slack group for Grav and send a direct message there. They using the same names as here.
