### ISSUE TITLE
Does not sync with bitbucket config

### ISSUE THREAD

**Issue by lianhuilui** [trilbymedia/grav-plugin-git-sync#62]
[git 1.9.1]
I have configured the plugin properly and set up webhook on bitbucket. The response for webhook is `{"status":"success","message":"GitSync completed the synchronization"}`

The sync does not happen from or to the server.
I have tried:
- editing posts from bitbucket. (the website does not pull)
- pushing changes from localhost. (the website does not pull)
- making changes from the admin panel. (the website does not push)

I enabled git command logging but it does not show anywhere (?)

The only way that works now is to run `bin/plugin git-sync sync` on the website manually.

**Comment by lianhuilui** [comment]
Actually, it was not because of bitbucket config but the custom url I've set for the Admin Panel. It seems `/admin` is hard coded in the plugin. I guess that's a different issue.

**Comment by w00fz** [comment]
Oh is it? I must have missed it. Please open an issue about that so I won't forget!

Glad you resolved!
