### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by drnasin** [trilbymedia/grav-plugin-git-sync#64]
Seems like the plugin is pretty unstable. It will work for a few days then all of a sudden I get:

fatal: unable to create thread: Resource temporarily unavailable fatal: The remote end hung up unexpectedly fatal: The remote end hung up unexpectedly fatal: The remote end hung up unexpectedly error: failed to push some refs to

For every "save" I do. I checked everything on github end, I used wizard again...but every time you want to save you get this error.  Had to disable the plugin for now...

I just remembered 2 days ago I enabled 2FA on my github account. Could that be the problem? But I'm using access token so it should work...

**Comment by w00fz** [comment]
Try testing the connection from the wizard to make sure there are no issues there.
Also that error mostly sounds like either slow connection on your end or heavy load on github. (I know this was a while back)

Is this still an issue?

**Comment by w00fz** [comment]
Feel free to reopen if this is still an issue.
