### ISSUE TITLE
Add support for Gogs/Gitea

### ISSUE THREAD

**Issue by toXel** [trilbymedia/grav-plugin-git-sync#7]
[Gogs](https://gogs.io/) is a self-hosted Git server and web interface written in Go. It's very GitHub-ish and easy to use. [Gitea](https://gitea.io/) is the community-managed fork of Gogs.

It would be very nice to have those services supported by this plugin!

**Comment by w00fz** [comment]
Hey there @toXel. Even though it's not in the list of repository available, any self hosted git server or remote service should still be supported.

The only different thing is you won't have the handy step-by-step tutorials in the wizard as you set the plugin up. However, if you select GitHub and put your Gogs/Gitea user/password and follow the GitHub steps, you should be able to figure out how this should be setup on Gogs/Gitea the same way.

Really the only thing you need to figure out is how to add a webhook in those services, other than that it's all the same.

This brings up a good point where perhaps there should be an "Other..." option to make the process more clear that GitSync is not strictly tied to only the 3 shown services but can be used with any.

Please give it a try and let me know if this all works, I see no reason why it wouldn't!

Thanks.

**Comment by toXel** [comment]
Okay thanks for the information I will try it!

**Comment by w00fz** [comment]
Cool, let me know if you succeed!

**Comment by erlepereira** [comment]
Thanks for a great plugin. I wanted to add my 2c in... it was pretty straight forward to use it with gogs .. i just used the gitlab link (though I think any could be used) .. The suggestion of other/advanced with just the options would suffice... * I could probably work on it and send a pull request if needed

**Comment by w00fz** [comment]
That would be nice! Yes any link can be used. The reason github, gitlab and bitbucket are the only ones listed is mostly for the documentation that helps in the wizard. It would be useful If in the documentation steps for the "Others..." provider,   generic guidance was included to help with what to look for and what to expect. For instance looking for webhooks settings for adding the callback URL would most likely be in some settings area of the repository, etc.

**Comment by erlepereira** [comment]
have sent the first set of changes in this pull request... with some screenshots  https://github.com/trilbymedia/grav-plugin-git-sync/pull/22

**Comment by w00fz** [comment]
Amazing job Erle! 

Thank you.

**Comment by GwynethLlewelyn** [comment]
First of all, thanks for this amazing plugin! 🥇 

I'm aware that I'm piping in late, but... when using Gogs with 2FA (a relatively new feature), there seems to be some difficulty in getting GitSync to correctly pass the token to Gogs (and, conversely, Gogs seems not to be able to use Grav's webhook). Of course, this could be a Gogs issue — and not a problem with GitSync. I'm just wondering if there is a way of looking at the logs and figuring out what is wrong (neither Grav nor Gogs seem to emit meaningful messages to the logs...)

**Comment by w00fz** [comment]
Hi @GwynethLlewelyn,
Unfortunately I am not too familiar with Gogs but if it's following the usual Git services standards it should all be the same.

A few versions back I added a way for logging GitSync commands as they happen. Try enabling the `Log Git Commands`, it's one of the last options in the GitSync plugins settings. Then you should be able to see what's going on in the `grav.log` file. All that is GitSync related is prefixed as so.
