### ISSUE TITLE
Add support for webhook secrets

### ISSUE THREAD

**Issue by pathmissing** [trilbymedia/grav-plugin-git-sync#72]
Currently, sending any type of http request to the webhook url will trigger a synchronization with the connected git repository. This makes it very easy for potential attackers to abuse as a denial of service attack. Although one can change the webhook url to make it hard to guess, this is not an ideal solution to the underlying problem (not to mention that this would only be effective when using the https protocol).

I would suggest to make use of webhook secrets which are already commonly supported by many providers like Github or Gitlab.

**Comment by w00fz** [comment]
Thanks @pathmissing this is now implemented.
Also Webhook is now auto-generated making it more robust and secure.
