### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by ZapTechAdmin** [trilbymedia/grav-plugin-git-sync#76]
When trying to set up git-sync with my gitlab repo, i get the following error
fatal: unable to access 'https://[username]:[password]@gitlab.com/zaptechadmin/zaptech.git/': SSL certificate problem: unable to get local issuer certificate
any ideas?

P.S. I have hidden the username and password, but they are correct.

**Comment by DanielSokil** [comment]
Disable `SSL verification` when creating system hook.
