### ISSUE TITLE
Doesn't Sync when adding plugins

### ISSUE THREAD

**Issue by cbates291** [trilbymedia/grav-plugin-git-sync#83]
Not sure if this is by choice, but I noticed that after I installed the plugin and it did its main first sync, I then went in and added a couple new plugins, etc. and configured then and then forced a sync and they never pushed. The UI said they did but bitbucket never showed the change being pushed. I then went and made a new page later and edited that, etc. and then it synced without issues. 

Just wondered if it should sync when adding plugins or not.

**Comment by paulhibbitts** [comment]
Hi @cbates291 , no it does not - the Git Sync plugin default settings only sync changes of Grav Pages. It is also possible to sync Theme files with some tweaks to the default Blueprint.
