### ISSUE TITLE
Slash is not add at the end of a custom git repository url for the "Edit this page" link

### ISSUE THREAD

**Issue by amiram** [trilbymedia/grav-plugin-git-sync#86]
Steps to reproduce:
1. Set the git remote url to "others" with the repo url without a slash at the end. 
e.g. http://tfs-host.com/tfs/MyCollection/MyProject/_git/wiki

2. Open a page and click on the "Edit this Page" link.

Expected result:
Link should be http://tfs-host.com/tfs/MyCollection/MyProject/_git/wiki/blob/master/pages

Actual Result:
Link is http://tfs-host.com/tfs/MyCollection/MyProject/_git/wikiblob/master/pages

Workaround:
Add a slash in the repo url
http://tfs-host.com/tfs/MyCollection/MyProject/_git/wiki/

BTW, it is not happening with github.

**Comment by paulhibbitts** [comment]
Hi @amiram , sounds like you were able to solve this issue by further adjusting the source git URL, is that right?

**Comment by paulhibbitts** [comment]
All three Git Sync themes have a Twig file to handle URL calc/display, which can be found in the folder `user/themes/THEMENAME/templates/partials/gitrepo_link.html.twig`

Your use case might be unique, so perhaps handling it by using a custom Git Sync URL in site config vs. adding a special case might be the best way to handle it? For sure I could also add a note in the readme for the theme as well, thanks.

**Comment by amiram** [comment]
Pardon me but I'm new to grav. I found the folder in my grav instance, but not in your repo.

**Comment by paulhibbitts** [comment]
No problem, which Git Sync theme of mine are you using?

**Comment by amiram** [comment]
learn-2

**Comment by paulhibbitts** [comment]
Learn 2, not learn 2 with Git Sync? Oh, if that is the case this is the repo: https://github.com/getgrav/grav-theme-learn2

My Learn 2 with Git Sync theme contains a lot of auto-calculation stuff for URLs https://github.com/hibbitts-design/grav-theme-learn2-git-sync so please make sure you've got the right theme🙂

**Comment by amiram** [comment]
Oh I got it now. I'm using learn2 with git sync. I'll find it there. Thanks

**Comment by paulhibbitts** [comment]
Great! FYI, in the Learn2 with Git Sync Theme settings you can modify the base Edit this Page in Git URL

**Comment by paulhibbitts** [comment]
If you want to pursue this, perhaps close this issue here and open a new one in my repo? https://github.com/hibbitts-design/grav-theme-learn2-git-sync Thanks.
