### ISSUE TITLE
The "Edit this page" address for TFS is wrong

### ISSUE THREAD

**Issue by amiram** [trilbymedia/grav-plugin-git-sync#87]
The regular link to adit a page is
http://[repo-address]/blob/master/pages/folder/docs.md

For tfs it should be:
http://[repo-address]?path=%2Fpages%2Ffolder%2Fdocs.md&_a=contents

If it is not on the master branch, branch name should be added with GB prefix.
For branch dev:
http://[repo-address]?path=%2Fpages%2Ffolder%2Fdocs.md&_a=contents&version=GBdev

**Comment by paulhibbitts** [comment]
Hi @amiram , by the sounds of it this is an issue with one of my themes that automatically create "Edit this Page" links for use with the Git Sync Plugin (Open Course Hub, Learn2 with Git Sync, and Open Publishing Space)? I've only done testing with standard GitHub, GitLab, and Bitbucket repositories. I have no experience with TFS.

All of the logic is actually handled by the theme, so customizations are possible. If you would like to further discuss please leave an issue on the appropriate theme repo or connect with me in the Grav Slack room (https://getgrav.org/slack), thanks.

**Comment by amiram** [comment]
Thanks. I'll close this too and look in the learn2 repo.
