### ISSUE TITLE
Git-sync looks like completely broken in Grav 1.4.1

### ISSUE THREAD

**Issue by welcoMattic** [trilbymedia/grav-plugin-git-sync#91]
Since the last update of Grav, I'm trying to use git-sync, but I lose all of my content!!

Steps to reproduce:

- Create a fresh Grav 1.4.1 site with admin skeleton
- Add some pages
- Install git-sync
- Configure it to a fresh new GitHub repo (only used for sync, not to version the site)
- Edit and save a page
- 💥 

Let me know if you need more information

**Comment by paulhibbitts** [comment]
Hi @welcoMattic I am not a dev but I've been using Git Sync with 1.41 for all of my skeletons and so far so good, might have something else changed? Maybe try one of my skeletons with 1.41 + Git Sync as a test, like this Open Course Hub https://getgrav.org/downloads/skeletons ?

**Comment by AlexandreRio** [comment]
Does your new github repo contains at least one commit?
The doc says: ` GitSync won't work unless the repository has at least one commit.`

**Comment by sm-peteradams** [comment]
Mine contains at least one commit but I get a timeout error using Grav 1.4.1

**Comment by welcoMattic** [comment]
It's better with a git-sync to another repo, instead of the one with Grav code.
