### ISSUE TITLE
A different admin-path breaks the plugin

### ISSUE THREAD

**Issue by Yethiel** [trilbymedia/grav-plugin-git-sync#94]
For security reasons, I changed my Administrator path from `/admin` to something else.
This seems to break Git Sync entirely. The settings page looks garbled and the wizard shows up every time. The synchronization also doesn't work (no error, it says it finished successfully but nothing happens).
Changing it back to `admin` makes everything work again.

Git Sync v1.0.4
Grav v1.4.3
Admin v1.7.4

**Comment by tribut** [comment]
Duplicate of #27, fixed in #77 (not yet merged).

**Comment by leotiger** [comment]
A PR for this is available. I had to apply the proposed code changes manually and now the sync works and js error is gone. As the PR is in the queue since last November... would be a good idea to offer a maintenance release.

**Comment by w00fz** [comment]
Sorry this has been taking so long. I'm going through all the issues now and implementing some new cool features!

Fixed with #77
