### ISSUE TITLE
`Synchronize` fails silently from Admin plugin

### ISSUE THREAD

**Issue by bsheen** [trilbymedia/grav-plugin-git-sync#96]
Running the `bin/plugin git-sync sync` command from the CLI yields:
```
Synchronizing with https://github.com/code-heroes-pty-ltd/Website.git
Changes detected, adding and committing...
                                                                   
  [RuntimeException]                                                           
  *** Please tell me who you are.                                              
  Run                                                                          
    git config --global user.email "you@example.com"                           
    git config --global user.name "Your Name"                                  
  to set your account's default identity.                                      
  Omit --global to set the identity only in this repository.                   
  fatal: unable to auto-detect email address (got 'root@0f249caa6b8b.(none)')  
                                                                               
sync
```
However, from `http://localhost/admin/plugins/git-sync` in the Admin if I click `Synchronize` I get the following message:
`GitSync has successfully synchronized with the repository`
But changes are not reflected in the repo on GitHub.

When I execute the git config commands as suggested both the CLI command and `Synchronize` button in the Admin plugin work as expected and the changes are reflected in the repo.

Obviously, this is easily dealt with by setting git user.email and user.name via the config command. However, I'm reporting this as better reporting of the error in the Admin plugin would be beneficial for those attempting to track down why syncing is not working from the Admin plugin.

**Comment by bsheen** [comment]
@w00fz to add further context, I was installing the plugin into a Grav installation which is part of a Docker container. Hence, git wasn't setup as it would be as would be on a development machine. 

As you say, it would be helpful to get an appropriate error message in the admin to point the user quickly to a resolution.

**Comment by w00fz** [comment]
Do you know if there's a way to get this reproduced after git is all set?
I'm trying to get to that state on my local but I can't get it erroring out.

I removed my user/email from `~/.gitconfig` and `user/.git/config` but still goes through the synchronization.

**Comment by bsheen** [comment]
You could look at spinning Grav up inside of a Docker container from one of the public images:
https://hub.docker.com/r/benjick/grav/

**Comment by bsheen** [comment]
@w00fz thanks for your efforts. This issue/discussion might help anyone in future facing the same find a resolution.
